### ISSUE TITLE
Bibtex cross-ref feature

### ISSUE THREAD

**Issue by flopraden** [sciunto-org/python-bibtexparser#104]
Hi, 

I'm not sure It's in bibtexparser scope for cross-ref but it could be implemented in bibdatabase.

I'm just opening an issue to discuss about it.

**Comment by sciunto** [comment]
I don't use crossref. Could you elaborate on the features you would like to see? Like a counter?

**Comment by flopraden** [comment]
no, crossref is a way to add missing field from another reference.
It's almost finish (unittest to do, and test it)

**Comment by sciunto** [comment]
See #109
