### ISSUE TITLE
Dependency in __init__ means pip install fails

### ISSUE THREAD

**Issue by JordanReiter** [sciunto-org/python-bibtexparser#110]
pyparsing is a dependency for bibtexparser and is noted as such in setup.py.

**However**, setup.py gets the version number from __init__, which in turn imports bibtexexpression, which imports pyparsing.

As a result, in an install where pyparsing is not already installed, attempting to install via pip will result in an error:

    $ cd /path/to/project
    $ virtualenv .
    $ source ./bin/activate
    $ pip install -e git+https://github.com/sciunto-org/python-bibtexparser.git#egg=bibtexparser
    Obtaining bibtexparser from git+https://github.com/sciunto-org/python-bibtexparser.git#egg=bibtexparser
      Updating ./src/bibtexparser clone
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "<string>", line 20, in <module>
          File "/path/to/project/src/bibtexparser/setup.py", line 8, in <module>
            from bibtexparser import __version__ as version
          File "bibtexparser/__init__.py", line 27, in <module>
            from . import bibdatabase, bibtexexpression, bparser, bwriter, latexenc, customization
          File "bibtexparser/bibtexexpression.py", line 1, in <module>
            import pyparsing as pp
        ImportError: No module named pyparsing
    
        ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /path/to/project/src/bibtexparser

**Comment by sciunto** [comment]
Well spoted. Let's try with #111

**Comment by sciunto** [comment]
Looks fixed on my side. I close this.
