### ISSUE TITLE
Writing a modified BibTeX

### ISSUE THREAD

**Issue by Phyks** [sciunto-org/python-bibtexparser#114]
Hi,

As is, if I understood correctly, the writer has to take a `BibDatabase` object. Then, I can simply:

```python3
bib_db = bibtexparser.loads(SOME_BIBTEX)
bib_db.entries[0]["SOME_FIELD"] = SOME_NEW_VALUE
bibtexparser.dumps(bib_db)
```
and it works fine.

Now, the tricky part is when I want to do it with a part of a BibTeX file. Say I have a BibTeX file with two entries, and want to extract a single entry. I can

```python3
bib_db = bibtexparser.loads(SOME_BIBTEX)
entry = bib_db.entries[SOME_ID]
```

But my `entry` is a `dict` and not a `BibDatabase` object anymore. So I cannot write it any longer.

For me, there is an inconsistency here in the API, and there should be either a function to extract a `BibDatabase` object from a subset of a BibTeX file, or recreate a BibDatabase object from an entry dict, or each entry should itself be a `BibDatabase` object, or something like this. But perhaps I missed something…

Thanks!

**Comment by sciunto** [comment]
I'm not sure to see the problem. If you look at https://bibtexparser.readthedocs.org/en/v0.6.2/tutorial.html#using-the-writer from a dict, a bibtexfile can be written. You just need to encapsulate your dictionary in a list of a single element no? Am I missing something?

**Comment by Phyks** [comment]
Indeed, I missed this part in the doc and I can do the following:
```python
bib = bibtexparser.load(open("/tmp/test.bib"))  # test.bib contains multiple entries
entry = bib.entries[0]

db = bibtexparser.bibdatabase.BibDatabase()
db.entries = [bib.entries[0]]
bibtexparser.dumps(db)
```

and it works.

However, I would find it more natural and user-friendly to do:
```python
bib = bibtexparser.load(open("/tmp/test.bib"))  # test.bib contains multiple entries
entry = bib.bibdb_entries[0]  # bibdb_entries (or anything else) would be a collection of BibDatabase objects
bibtexparser.dumps(entry)
```

I mean, if I understood correctly the code, `BibDatabase` could be used to represent any collection of entries, then I would find it useful to not distinguish between a BibTeX file having a single entry and an entry from a BibTeX file having multiple entries.

**Comment by sciunto** [comment]
You need to use a slice

```
# select the first entry
entry[0:1]
# select the two first entries
entry[0:2]
```

A single entry is a particular case and must be treated as it.

**Comment by Phyks** [comment]
Hmm, not sure we understood each other…

```python
bib = bibtexparser.load(open("/tmp/test.bib"))  # test.bib contains multiple entries
entry = bib.bibdb_entries[0:1]  # bibdb_entries (or anything else) would be a collection of BibDatabase objects
bibtexparser.dumps(entry)
```

does not work neither. I still have to manually rebuild a `BibDatabase` object, which seems to be really painful and to break the homogeneity of the API, in my opinion.

**Comment by sciunto** [comment]
OK. What you want is actually different. You want more methods in the bibdatabase class to alter the database.

**Comment by sciunto** [comment]
I opened a new issue.

**Comment by Phyks** [comment]
Not sure to follow you… But I guess if I could slice a `BibDatabase` and still have a `BibDatabase`, that would do the trick.

**Comment by sciunto** [comment]
Yes, that's the idea...

**Comment by Phyks** [comment]
Ok!
