### ISSUE TITLE
Strip title of "{", "}" and similar

### ISSUE THREAD

**Issue by MartinThoma** [sciunto-org/python-bibtexparser#116]
I've just tried bibtexparser for https://github.com/MartinThoma/algorithms/tree/master/bib2html and I noticed that `entry.title` can be something like `On-line {Recognition} of {Handwritten} {Mathematical} {Symbols}.`.

Is it possible to strip those / to make the title similar to what it gets rendered to?

**Comment by sciunto** [comment]
@MartinThoma I'm not sure to understand. Can you provide a minimal example with the expected output please?

**Comment by MartinThoma** [comment]
@sciunto Sure.

Reading the bibtex-file

```bibtex
@MastersThesis{Thoma:2014-bs,
  Title                    = {On-line {Recognition} of {Handwritten} {Mathematical} {Symbols}},
  Author                   = {Martin Thoma},
  School                   = {Karlsruhe Institute of Technology},
  Year                     = {2014},

  Address                  = {Karlsruhe, Germany},
  Month                    = nov,
  Type                     = {Bachelor’s Thesis},

  Pages                    = {58},
  Pdf                      = {http://arxiv.org/pdf/1511.09030v1},
  Url                      = {http://martin-thoma.com/write-math}
}
```

with code like

```python
with open(path) as bibtex_file:
    bibtex_str = bibtex_file.read()
bib_database = bibtexparser.loads(bibtex_str)
entry = bib_database.entries[0]

# what I would like to have:
print(entry['plain_title'])
```

giving

```text
On-line Recognition of Handwritten Mathematical Symbols
```

instead of what `entry['title']` gives:

```text
On-line {Recognition} of {Handwritten} {Mathematical} {Symbols}
```

So it should be an alternative to

**Comment by nils-werner** [comment]
I believe curly braces are allowed in any field, so you should not only allow for a special field `plain_title` but maybe create a new parser customization that lets you enable this feature on all fields.

**Comment by Phyks** [comment]
@MartinThoma I just made an implementation of such a feature in https://github.com/Phyks/python-bibtexparser/commit/44d1a4571f9e611db083631807972828bedf6353. Could you check it matches your expectations? Thanks!
