### ISSUE TITLE
bibtexparser.load miss the first bib when the file has 0xFEFF BOM

### ISSUE THREAD

**Issue by xunkai55** [sciunto-org/python-bibtexparser#119]
The file was encoded in utf-8 with 0xFEFF BOM with 21 bib.
But when I used `bibtexparser.load(f)`, only last 20 of them could be parsed.
After I had manually removed the BOM, 21 of them were parsed correctly.

**Comment by sciunto** [comment]
I seems to be fixed in master. See #128.
Feel free to reopen if it's not for you.

Thanks.
