### ISSUE TITLE
bad installation instruction

### ISSUE THREAD

**Issue by keithbriggs** [sciunto-org/python-bibtexparser#122]
At https://bibtexparser.readthedocs.org/en/v0.6.2/install.html, it says:

> python setup.py install --root=/usr/local/bin

I did this, but it then writes files into

/usr/local/bin/usr/local/lib/python2.7/dist-packages/

which is not a sensible place.

**Comment by sciunto** [comment]
Thank you.  Fixed in #123 with further improvements
