### ISSUE TITLE
Can't parse bibtex file

### ISSUE THREAD

**Issue by Makman2** [sciunto-org/python-bibtexparser#124]
Hi :)

This bibtex file errors out:

```
@article{ art,
Author = {No, one},
Title = {{Blah blah blah blah blah blah blah blah blah blah blah blah blah blah
   @blah blah blah blah blah.}},
}
```

loading via 

```python
import bibtexparser
with open("bibtexfail.bib") as fl:
    db = bibtexparser.load(fl)
```

but it fails with:

```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/lib/python3.4/site-packages/bibtexparser/__init__.py", line 59, in load
    return parser.parse_file(bibtex_file)
  File "/usr/lib/python3.4/site-packages/bibtexparser/bparser.py", line 130, in parse_file
    return self.parse(file.read())
  File "/usr/lib/python3.4/site-packages/bibtexparser/bparser.py", line 119, in parse
    self._parse_records(customization=self.customization)
  File "/usr/lib/python3.4/site-packages/bibtexparser/bparser.py", line 171, in _parse_records
    _add_parsed_record(record, records)
  File "/usr/lib/python3.4/site-packages/bibtexparser/bparser.py", line 144, in _add_parsed_record
    parsed = self._parse_record(record, customization=customization)
  File "/usr/lib/python3.4/site-packages/bibtexparser/bparser.py", line 248, in _parse_record
    bibtype, id = kv.split('{', 1)
ValueError: need more than 1 value to unpack
```

Removing the `@` before the `blah`s makes the file possible to parse.
Is the bib-file I've provided invalid because of the `@`?

I'm using version 0.6.2 (installed via pip)

Thanks in advance :)

**Comment by sils1297** [comment]
@Makman2 apparently people seem to have worked around this area of the code lately but no release happened which is why the function in your traceback doesn't exist in the latest version of that file. (It does if you to to the last release.) Can you try reproducing the issue with the devel stuff from master? Otherwise we might want to

a) search for a quick fix
b) search for another lib

though I like this lib, especially since it makes it so easy to convert to dict.

**Comment by Makman2** [comment]
Yeah the current dev-head has solved this issue^^

Would be nice anyway to make a release then so one doesn't need to install it manually via the git clone^^

**Comment by sciunto** [comment]
Yes, but we still have issues to fix ;)

**Comment by sils1297** [comment]
Ah I just talked with @Makman2 apparently the current dev version isn't usable, is there anything we can use that does not have this issue?

**Comment by sciunto** [comment]
@sils1297 @Makman2 Please, give me more details. with the dev version, I got

```
[{'title': '{Blah blah blah blah blah blah blah blah blah blah blah blah blah blah\n@blah blah blah blah blah.}', 'author': 'No, one', 'ID': 'art', 'ENTRYTYPE': 'article'}]
```

from

```
bibtex = """
@article{ art,
Author = {No, one},
Title = {{Blah blah blah blah blah blah blah blah blah blah blah blah blah blah
   @blah blah blah blah blah.}},
}
"""

with open('/tmp/bibtex.bib', 'w') as bibfile:
    bibfile.write(bibtex)


import bibtexparser

with open('/tmp/bibtex.bib') as bibtex_file:
    bibtex_str = bibtex_file.read()

bib_database = bibtexparser.loads(bibtex_str)
print(bib_database.entries)
```

**Comment by Makman2** [comment]
This is not about this issue in fact. The example here works with the dev version, but my real source doesn't get parsed completely any more. It seems bibtexparser has problems with newlines and stuff (on first sight). I couldn't track it down and I'm not sure if I'm allowed to provide the original source here^^

**Comment by sciunto** [comment]
If you can build a minimal exemple, that would be helpful :)

Thank you.

**Comment by Makman2** [comment]
If you want you can send me a mail and I would send you back my original sample (but if you build tests out if it be sure to not use actual information out of the file) :+1:

**Comment by sciunto** [comment]
OK, I'll look at that.

**Comment by sciunto** [comment]
The reason is that the parser didn't consider a field with parenthesis as a valid field. I made a patch (#124). You must be able to parse your file now.

**Comment by sciunto** [comment]
Please, let me now if you still see a problem. Thanks.

**Comment by Makman2** [comment]
yeah works smoothly now, many thanks :D
