### ISSUE TITLE
few enhancements to decide based on #137 (name features)

### ISSUE THREAD

**Issue by sciunto** [sciunto-org/python-bibtexparser#138]
From #137 
- [ ] Mention that in the tutorial?
- [ ] decide what we do about `customization.getnames()` and related tests.
- [ ] review #9 
- [ ] update CHANGELOG

**Comment by bcbnz** [comment]
#9 should be fixable once pull request #140 is sorted (I did some renaming etc there). I'll take a look at it in the next few days.

The customization.author() and customization.editor() functions can also be rewritten in terms of the utils.splitnames() added in #140 to make them more robust. I'll also have a go at that.

I've updated the CHANGELOG to mention my additions in #140.
