### ISSUE TITLE
parsing json data

### ISSUE THREAD

**Issue by rudrab** [sciunto-org/python-bibtexparser#142]
Hi,
since bibtexparser outputs data as JSON, I wonder, if it can parse JSON as input as well, as many journal api outputs data as json (say, crossref).
I was trying to do that with a simple code as:

```
#! /usr/bin/python3

import bibtexparser
import json
from pprint import pprint

# json_file='a.json'
json_file='myj.json'
cube='1'

json_data=open(json_file)
data = json.load(json_data)
pprint(data)
bib_database = bibtexparser.loads(str(json_data))
print(bib_database.entries)
json_data.close()
```

but that does not return anything. Am I knocking at a wrong place?

**Comment by MiWeiss** [comment]
At the moment, this is not supported. 

You migh be able to manually construct a bibdatabase from your loaded json if you really need to.
