### ISSUE TITLE
get line at which entry is recorded ?

### ISSUE THREAD

**Issue by teto** [sciunto-org/python-bibtexparser#144]
Fro mthe doc, it doesn't seem to know at what line of the .bib file the entry was written.
This is for use in a YouCompleteMe  completer https://github.com/Cocophotos/vim-ycm-latex-semantic-completer/issues/2

**Comment by Phyks** [comment]
This seems to be easy to do. What is the required output? Would first line of the entry (line number of the `@SOMETHING`) be ok?

**Comment by teto** [comment]
not using this anymore
