### ISSUE TITLE
Unable to parse single line entries

### ISSUE THREAD

**Issue by drufat** [sciunto-org/python-bibtexparser#149]
The program fails silenetly on the following input

```
import bibtexparser

s = bibtexparser.loads("""

    @article{A, title={Article}}

""")

print (s.entries)
```

Even though it should be able to parse the expression, it prints out an empty list of entries.

**Comment by Phyks** [comment]
Using the latest commit on the `master` branch,

```
>>> import bibtexparser
>>>
>>> s = bibtexparser.loads("""
...
...     @article{A, title={Article}}
...
... """)
>>>
>>> print (s.entries)
[{'ID': u'A', 'ENTRYTYPE': u'article', u'title': u'Article'}]
```

It should be working. The latest release is quite old and does not match the latest version of the code, see https://github.com/sciunto-org/python-bibtexparser/issues/69 as well.

**Comment by sciunto** [comment]
I close, feel free to reopen if necessary.
