### ISSUE TITLE
@Strings parsed incorrectly if beginning with `{Example}`

### ISSUE THREAD

**Issue by kno10** [sciunto-org/python-bibtexparser#153]
The following two strings are incorrectly parsed:
```
@String{TODS = {{ACM} Transactions on Database Systems ({TODS})}}
```

This will incorrectly be parsed as
```
u'journal': u'ACM} Transactions on Database Systems ({TODS})',
```
I.e. the initial `{` is lost.

The same happens with trailing quotes:
```
@STRING{LWDA16 = {Proceedings of the Conference "Lernen, Wissen, Daten, Analysen"}}
```
will lose the trailing `"`. bibtexparser should only remove _at most one_ set of _matching_ quotes.

**Comment by omangin** [comment]
Hi @kno10. I just tried the example you give and get the correct result.
```python
>>> import bibtexparser

>>> b = bibtexparser.loads("@String{TODS = {{ACM} Transactions on Database Systems ({TODS})}}")

>>> b.strings
OrderedDict([('tods', '{ACM} Transactions on Database Systems ({TODS})')])
```
What version of bibtexparser are you using? This issue has probably been solved in the current version. If not, I'll look into it.

**Comment by kno10** [comment]
Using 0.6.2 from the Ubuntu package 0.6.2-2:
```
>>> import bibtexparser
>>> b = bibtexparser.loads("@String{TODS = {{ACM} Transactions on Database Systems ({TODS})}}")
>>> b.strings
OrderedDict([('tods', 'ACM} Transactions on Database Systems ({TODS})')])
```
0.6.2 seems to be the latest release.

**Comment by omangin** [comment]
Indeed, I get the issue too on the v0.6.2 but it has been solved since then. The best thing to do before v0.7 is out is probably that you switch to the current git version of the software.
