### ISSUE TITLE
Inconsistent results using `bibtexparser.latex_to_unicode`

### ISSUE THREAD

**Issue by tim6her** [sciunto-org/python-bibtexparser#161]
Thanks for writing and maintaining this package!

I found that using `bibtexparser.latex_to_unicode` yields inconsistent results:

    >>> latex_to_unicode(r"p\^{a}t\'{e}")
    'pâté'
    >>> latex_to_unicode(r"\^{i}le")
    '{î}le'

Why are there braces around i-circumflex but not around a-circumflex or e-acut?

**Comment by Phyks** [comment]
Indeed, I think we should strip braces from the ouput. Will fix it in my next PR.

**Comment by Phyks** [comment]
See https://github.com/sciunto-org/python-bibtexparser/pull/162. Should be fixed.
