### ISSUE TITLE
Records with no ID parsed incorrectly

### ISSUE THREAD

**Issue by mikethicke** [sciunto-org/python-bibtexparser#163]
Given the following record:

> @misc{
author = {AMAP},
title = {Summary – The Greenland Ice Sheet in a Changing Climate: Snow, Water, Ice and Permafrost in the Arctic (SWIPA)},
publisher = {Arctic Monitoring and Assessment Programme (AMAP)},
pages = {22 pp.},
year = {2009},
type = {Generic},
}

The parser sets ID as "author = {AMAP" and doesn't recognize the author field.

Changing `re.split(',\s*\n|\n\s*,', record)` to `re.split('(?<={)\s*\n|,\s*\n|\n\s*,', record)` line 239 of bparser.py seems to fix the problem.

**Comment by Phyks** [comment]
Not sure we want to support this. Are these valid Bibtex entries? (http://www.bibtex.org/Format/ seems to indicate it is not)

@sciunto @omangin

**Comment by omangin** [comment]
Yes, I don't think this is a valid entry. Or if it is, the parser indeed does not support it yet.

We might consider, though, making sure that the parser fails on this. It currently accepts any string up to the next `,` as a valid entry key, which is probably too permissive.

**Comment by mikethicke** [comment]
I'm parsing .bib files downloaded from a large organization (http://ipcc.ch/report/ar5/wg1/). I don't know how they are generated, but if you don't plan to support this (mal)formatting perhaps an exception should be thrown?

**Comment by sciunto** [comment]
+1 to fail gracefully on this.

**Comment by Phyks** [comment]
The problem I see with supporting it is that if you have multiple such entries in the same bibtex file, information will be lost (as all these entries will have the same undefined ID).

I can try to write something to throw an exception and fail gracefully on this.

Concerning the main issue of @mikethicke, what are you trying to do with these entries and Bibtexparser? Is failing on this ok for you? Else, I would be interested in your use case to look for a workaround.

**Comment by sciunto** [comment]
Eventually, bibtexparser may return to the user the faulty entries with the exception, such that the user can do whatever s/he wants with them.

**Comment by Phyks** [comment]
Ok, so it seems replacing line 141 in `bibtexparser/bibtexexpression.py` by

```
        key = pp.SkipTo(',', failOn='=')('Key')  # Exclude @',\#}{~%
```

that is, failing on `=`, does the trick. Failing on new line is not really nice, as it would match the bibtex entry:

```

**Comment by Phyks** [comment]
FTR, here is the output of Bibtex on the entry from the OP:

```
This is BibTeX, Version 0.99d (TeX Live 2016)
The top-level auxiliary file: test.aux
The style file: plain.bst
I found no \citation commands---while reading file test.aux
Database file #1: test.bib
I was expecting a `,' or a `}'---line 2 of file test.bib
 :     author
 :            = {AMAP},
I'm skipping whatever remains of this entry
(There were 2 error messages)
```

But both

```bibtex
@misc{
    toto=a,
    author = {AMAP},
    title = {Summary – The Greenland Ice Sheet in a Changing Climate: Snow, Water, Ice and Permafrost in the Arctic (SWIPA)},
    publisher = {Arctic Monitoring and Assessment Programme (AMAP)},
    pages = {22 pp.},
    year = {2009},
    type = {Generic},
}
``` 

and

```bibtex
@misc{toto=a,
    author = {AMAP},
    title = {Summary – The Greenland Ice Sheet in a Changing Climate: Snow, Water, Ice and Permafrost in the Arctic (SWIPA)},
    publisher = {Arctic Monitoring and Assessment Programme (AMAP)},
    pages = {22 pp.},
    year = {2009},
    type = {Generic},
}
```

are valid entries with valid keys. So I guess the check on `=` is not good enough.

**Comment by omangin** [comment]
Another way of approaching the issue would be to make the citekey optional at the syntax level and to check its presence at the semantic level. That way we can easily chose the behavior such as skipping the entry or raising an error.

**Comment by benureau** [comment]
Btw, this entry also fails:
```
@BOOK{, title = "bla"}
```
with `'NoneType' object has no attribute 'strip'`

**Comment by omangin** [comment]
See #213 for a slightly stronger enforcement on citekeys.

However this will not change much in the behavior of the parser since the way it is implemented right now is to consider blocks that could not be parsed as implicit comments. Because of that, the parser silently ignores most failures while parsing.

I believe this is not a really desirable behavior and we should probably change the default to something stricter (eventually having a `permissive_implicit_comments` option if deemed necessary). The remaining question is what should then be considered an implicit comment?

In my opinion a reasonable answer would be anything not starting by `@alpha{`.

Any thought on this?
