### ISSUE TITLE
pypy3 has been removed in travis

### ISSUE THREAD

**Issue by sciunto** [sciunto-org/python-bibtexparser#166]
Due to https://github.com/travis-ci/travis-ci/issues/7771

To revert when fixed.

**Comment by Phyks** [comment]
Workaround is https://github.com/ragzilla/ciscoconfparse/commit/e3cec3630be1c228e4f4c0db623aa8054f27613f. Maybe it should be better to use this style?

**Comment by sciunto** [comment]
@Phyks Yes. + open a ticket to fix that in the future.

**Comment by Phyks** [comment]
Feedback from Travis-CI support:

> At the moment, the following pypy3 versions are available:
> pypy3-2.4.0          12.04 14.04
> pypy3-2.4            12.04 14.04
> pypy3.3-5.2-alpha1   12.04 14.04
> pypy3.3-5.5-alpha    12.04 14.04
> pypy3.5                    14.04
> pypy3.5-5.7.1-beta         14.04
> pypy3.5-5.8.0        12.04 14.04

I updated the PR accordingly, to make pypy3 tests pass again. pypy2 still not passing :/
