### ISSUE TITLE
entries with ID as key

### ISSUE THREAD

**Issue by akshaybabloo** [sciunto-org/python-bibtexparser#169]
Is it possible to customise the parser with a custom output, something like

```json
{
  "id_as_key": {
    "title": "some_title",
    "author": "authors name"
  },
  "id_as_key_2": {
    "title": "some_title",
    "author": "authors name"
  }
}
```

Or if not something by `ENTRYTYPE`?

**Comment by Phyks** [comment]
I'm not sure to understand, but I think you are looking for [entries_dict](https://github.com/sciunto-org/python-bibtexparser/blob/87e72d4ceeb83603efe7df4fdcd2ee531eb33680/bibtexparser/tests/test_bibdatabase.py#L21-L24).

**Comment by akshaybabloo** [comment]
@Phyks How would you use that? Could you give me an example?

**Comment by Phyks** [comment]
Typically,

```
import bibtexparser

with open('bibtex.bib') as bibtex_file:
    bibtex_str = bibtex_file.read()

bib_database = bibtexparser.loads(bibtex_str)
print(bib_database.entries_dict)
```
