### ISSUE TITLE
Lost of information while parsing

### ISSUE THREAD

**Issue by SamuelCabralCruz** [sciunto-org/python-bibtexparser#172]
# Issue
I observed that some information could be lost during the parsing of a BibTeX file due to early exiting of the ```_parse_record``` method.

# Study Case
Let say that we are parsing a BibTeX file containing the following entry:
> @book{booksR:Goulet:introR,
> title = {{Introduction à la programmation en R}},
> author = {{Vincent Goulet}},
> publisher = {{Bibliothèque et Archives Canada}},
> year = {2016},
> ISBN = {978-2-9811416-6-8},
> url = {\url{https://cran.r-project.org/doc/contrib/Goulet_introduction_programmation_R.pdf}}}

Even if it is not a common practice of writing an entry this way, the bibtexparser package should be able to handle it since it still is a valid BibTeX entry.

However, when I parse this entry using your package, I get the following parsed entry:
> Reference Instance
>  ID: 
> 	 booksR:Goulet:introR
>  ENTRY TYPE: 
> 	 book
>  Location: 
> 	 R/booksR.bib
>  Number of tags defined: 
> 	 7
>  Defined tags: 
> 	 author, entrytype, id, isbn, publisher, title, year
>  
> @book{booksR:Goulet:introR,
>  author = {Vincent Goulet},
>  isbn = {978-2-9811416-6-8},
>  publisher = {Bibliothèque et Archives Canada},
>  title = {Introduction à la programmation en R},
>  year = {2016}
> }
We clearly see that the URL field has been ignored.

# Analysis
At first, I thought I was caused by the special treatment done over the URL fields for homogenization purpose. I quickly realized that it was only a simple renaming. I then tried to use the ISBN field as the last field of the entry and the same behavior was observed (the ISBN field was ignored, but the URL field was now available). 

So I started digging deeper into the source code until I discovered how you were extracting each field from a "record/entry". The problem arises from the interaction of different details of the implementation.
- absence of ```}\n``` at the end of the record
- no replacement of ```}}``` by ```},\n}```
- val.count('{') != val.count('}') for the final kv

In short, because the last field of the entry is on the same line than the entry closing bracket and that the file do not have any empty row (```\n```) before the EOF, this information won't be parsed.

# Proposed Solution
Add an additional line break (```\n```) to each record parsed in the prepare record section of the ```_parse_record()``` method.
```{python}
# prepare record
record = '\n'.join([i.strip() for i in record.split('\n')])
# correction starts here
record += '\n'
# correction ends here
    if '}\n' in record:
        logger.debug('}\\n detected in the record. Clean up.')
        record = record.replace('\r\n', '\n').replace('\r', '\n').rstrip('\n')
        # treat the case for which the last line of the record
        # does not have a coma
        if record.endswith('}\n}') or record.endswith('}}'):
            logger.debug('Missing coma in the last line of the record. Fix it.')
            record = re.sub('}(\n|)}$', '},\n}', record)
```
For the moment, anybody facing the same problem or using the bibtexparser package to parse unknown BibTeX format should append a new line to the content of the files parsed before passing them to the bparser.

## Additional comments
1. The validation of standard BibTeX type should be done using a variable containing the list. This would make the package easier to maintain.
2. The line break could only be added to the content of the whole file instead of on each record since this problem will only occur for the last entry of any given file.

**Comment by Phyks** [comment]
Thanks for this really detailed issue!

Could you open a PR with your code proposal and put the Bibtex snippets in your study case in the unittests of this lib? That would be awesome and we could get it merged quickly! :)

**Comment by SamuelCabralCruz** [comment]
I will see to it.

**Comment by SamuelCabralCruz** [comment]
@Phyks I am new to GitHub and I just realized that the issue only concerns the last release. However, the master branch is far away from the last release. How should I proceed to do my pull request?

**Comment by Phyks** [comment]
Oh, then it is already fixed, and will soon land in pip with the new version. We should really flag a new release soon :)
