### ISSUE TITLE
Multiline fields containing braces not working

### ISSUE THREAD

**Issue by moble** [sciunto-org/python-bibtexparser#177]
I think the problem appears only when a field has two consecutive lines ending in `},`.  Here's my test case:

```python
import bibtexparser

bibtex_string = """@ARTICLE{Cesar2013,
  author = {{A},
            B. and {C},
            D.},
  title = {An amazing title},
}
"""

print(bibtexparser.loads(bibtex_string).entries[0]['author'])
```
The expected output is `{A}, B. and {C}, D.`; the actual output is just `{A}, B. and {C`.  If I remove either of the newlines in the `author` field, I get the expected output.

I'm running the current git version of this package on python 3.6.2.

**Comment by omangin** [comment]
Hi @moble, thanks for the detailed report. I tried running your code but I get the expected output. I'm also running python 3.6.2 and the latest git version of bibtexparser. I can however reproduce it from v0.6.2. Could you check that you're actually running the latest version by re-installing it from the git repository?

As a way to check, you can run `bibtexparser.__doc__`, it starts with `\nBibTeX <http://en.wikipedia.org/wiki/BibTeX>` for v0.6.2 and `\n`BibTeX <http://en.wikipedia.org/wiki/BibTeX>`_` for current git master.

**Comment by moble** [comment]
Sorry, you're right.  I guess I didn't restart python when I installed the git version over the pip version.  Thanks.
