### ISSUE TITLE
COPYING missing copyright notice

### ISSUE THREAD

**Issue by abspoel** [sciunto-org/python-bibtexparser#184]
For the BSD license, the first clause refers to a copyright notice:

> (1) Redistributions of source code must retain the above copyright
> notice, this list of conditions and the following disclaimer. 

Currently, this is missing in the COPYING file. This [can be fixed](https://en.wikipedia.org/wiki/BSD_licenses#3-clause_license_("BSD_License_2.0",_"Revised_BSD_License",_"New_BSD_License",_or_"Modified_BSD_License")) by putting the following at the start of the file:

> Copyright (c) \<year\>, \<copyright holder\>
> All rights reserved.

In this case, I guess the following [would work](https://ben.balter.com/2015/06/03/copyright-notices-for-websites-and-open-source-projects/):

> Copyright (c) 2012-2018, François Boulogne and the python-bibtexparser contributors
> All rights reserved.

**Comment by sciunto** [comment]
Thanks! I fixed it in master (https://github.com/sciunto-org/python-bibtexparser/commit/1ec45ec187f982a7cb679c3c868f855d793a61b2)
