### ISSUE TITLE
Struggle to parse because of an weird accent

### ISSUE THREAD

**Issue by aaa34169** [sciunto-org/python-bibtexparser#185]
Hello, 
first, i like your package and the associated documentation. 

i  stuggle to parse this bib entry 
`@article{MagalhA\poundses2016,
author = {{Bedran de Magalh{\~{a}}es}, Claudio Marcos and Kirkwood, Renata Noce},
file = {:C$\backslash$:/Users/HLS501/Documents/Bibliographie/mendeleyBiblio/Bedran de Magalh{\~{a}}es, Kirkwood - 2016 - Strategies to reduce joint load in the medial compartment of the knee during gait in individuals.pdf:pdf},
issn = {0103-5150},
journal = {Fisioterapia em Movimento},
keywords = {gait,kinetics,knee,osteoarthritis},
number = {4},
pages = {831--842},
title = {{Strategies to reduce joint load in the medial compartment of the knee during gait in individuals with osteoarthritis: a review of the literature}},
volume = {29},
year = {2016}
}`

the issue is from the accent tex coding `{\~{a}}`
i tried your documentation example, nothing work. 

For instance, when i  print  `entry[author`], python return 
`Bedran de Magalh{a}es, Claudio Marcos and Kirkwood, Renata Noce`

could you help me to fix that, please
fabien

**Comment by omangin** [comment]
Please re-open if you can reproduce the issue.
