### ISSUE TITLE
Is there any standard or common practice behind the `link` customization?

### ISSUE THREAD

**Issue by omangin** [sciunto-org/python-bibtexparser#188]
The [link customization](https://github.com/sciunto-org/python-bibtexparser/blob/master/bibtexparser/customization.py#L451) splits fields containing multiple links as well as an eventual anchor and format. However, I cannot find any reference to any such format specification.

Has anyone any idea on what this is based?

**Comment by MiWeiss** [comment]
stale & i doubt we'll find an answer for this ;-)
