### ISSUE TITLE
Version 1.0 crashes under python 2.7

### ISSUE THREAD

**Issue by levkowetz** [sciunto-org/python-bibtexparser#191]
Code to demonstrate:

```
#!/usr/bin/env python2
import bibtexparser
```

If you decide to stop supporting python2, the appropriate python version support should be indicated in the `setup.py` trove classifiers.

Personally, as an active maintainer of a large project which still runs under python2.7 and may take a lot of effort to convert, I'd be sad to see python 2.7 support go away.  I maintain tools such as [xml2rfc](https://pypi.python.org/pypi/xml2rfc/) with both 2.7 and 3.4 etc. support, so I know it's feasible.

**Comment by sciunto** [comment]
Thanks for the report. I fixed by releasing a new version.
Python2.7 support will be removed in a near future anyway https://pythonclock.org/

**Comment by levkowetz** [comment]
Thanks for the fix, and ack on pythonclock.  By that time, I'll have migrated.
