### ISSUE TITLE
KeyError and UndefinedString problem

### ISSUE THREAD

**Issue by ar-jan** [sciunto-org/python-bibtexparser#192]
Hi, I'm just getting started with bibtexparser. I run into the following:

```python
bibtex = """@book{lastname_2011,
  title = {My long {{Title}}: {{Subtitle Words}}},
  isbn = {978-00-000-0000-0},
  shorttitle = {My title},
  publisher = {{Publisher's name}},
  editor = {Lastname, Firstname and Lastname2, Firstname A.},
  month = jun,
  year = {2011}
}
"""

with open('test.bib', 'w') as bibfile:
    bibfile.write(bibtex)
```

```python
with open('test.bib') as bibtex_file:
    bib_database = bibtexparser.load(bibtex_file)

print(bib_database.entries)
```

> KeyError                                  Traceback (most recent call last)
> C:\Programs\Anaconda3\lib\site-packages\bibtexparser\bibdatabase.py in expand_string(self, name)
>     101             return BibDataStringExpression.expand_if_expression(
> --> 102                 self.strings[name])
>     103         except KeyError:
> 
> KeyError: 'jun'
> 
> During handling of the above exception, another exception occurred:

> 
> UndefinedString                           Traceback (most recent call last)
> <ipython-input-10-7d4857e06531> in <module>()
>       1 with open('test.bib') as bibtex_file:
> ----> 2     bib_database = bibtexparser.load(bibtex_file)

Should bibtexparser be able to deal with this kind of input?

**Comment by omangin** [comment]
Hi @ar-jan. The error occurs because `month = jun` relies on `jun` being defined as a latex string. Hence your entry is not a stricly well-defined bibtex entry. In order for this to parse you need to create a parser with the `common_strings` option set to `True`.

```python
with open('test.bib') as bibtex_file:
    bib_database = bibtexparser.bparser.BibTexParser(common_strings=True).parse_file(bibtex_file)
```

**Comment by omangin** [comment]
That's a good point. I'll fix the documentation.

**Comment by omangin** [comment]
@adinriv No this is not working. The option should be passed at the parser creation for the strings to be initialized in the `bibdatabase` object. This is done [there](https://github.com/sciunto-org/python-bibtexparser/blob/master/bibtexparser/bparser.py#L94-L95):
```python
if self.common_strings:
            self.bib_database.load_common_strings()
```

Overall setting the parameters directly as attributes should probably be deprecated since it is indeed confusing.

**Comment by adinriv** [comment]
Thanks, got it now.

I think it will be useful to update the documentation. In [here](https://bibtexparser.readthedocs.io/en/master/tutorial.html#tune-parser-s-options) it still appears as a valid option, and is confusing why one should work and the other wont.

**Comment by omangin** [comment]
Sure! Could you do a PR about it?
