### ISSUE TITLE
UndefinedString Error on Month field

### ISSUE THREAD

**Issue by andrejberg** [sciunto-org/python-bibtexparser#204]
bibtexparser version 1.0.1

When trying to load BibTex entries, that contain a month field I get:

UndefinedString u'apr'

for example.

Fix: Add after line 64 in bibtexparser/bibdatabase.py:

self.load_common_strings()

**Comment by adamheins** [comment]
You can also create your own parser object and set the `common_strings` flag to True. For example:
```python
import bibtexparser

parser = bibtexparser.bparser.BibTexParser(common_strings=True)

# Doesn't complain about "month = apr" field.
db = bibtexparser.loads('mybibtex.bib', parser=parser)
```

**Comment by omangin** [comment]
Indeed. And this is also related to what is discussed in #201 and #203. It is also mentioned in the documentation but that point should probably be improved. I will close the issue nevertheless.

**Comment by louismartin** [comment]
Same issue here, the custom parser solution seems to work, would be great if the error was more explicit from the start. :)
