### ISSUE TITLE
ENH: Optional last comma in BibTexWriter

### ISSUE THREAD

**Issue by u55** [sciunto-org/python-bibtexparser#206]
BibTeX allows the comma to be optional at the end of the last field in an entry. Currently, `BibTexWriter` only writes entries with this comma missing, but I would like to have the option of including it.  For example, both of these entries are valid:
```
@ARTICLE{Cesar2013,
  author = {Jean Cesar},
  title = {An amazing title}
}
@ARTICLE{Cesar2013,
  author = {Jean Cesar},
  title = {An amazing title},
}
```
Including the ending comma has the advantage that if I later manually add a new field at the end, I don't have to modify the previous line. This also makes for cleaner file diffs.

I am thinking of something as simple as adding `self.comma_last=False` to `BibTexWriter.__init__`, and modifying [the ending line of `BibTexWriter._entry_to_bibtex`](https://github.com/sciunto-org/python-bibtexparser/blob/f5b1bf8cceeba88367c9e1598133df83b60d80c7/bibtexparser/bwriter.py#L139) to be:

```python
if self.comma_last:
    bibtex += ",\n}\n" + self.entry_separator
else:
    bibtex += "\n}\n" + self.entry_separator
```
Thanks.

**Comment by sciunto** [comment]
Hi @u55 
Nice idea. Would you like to submit a PR please?

**Comment by keithbriggs** [comment]
A one-liner something like this would be more pythonic:

    bibtex += "%s\n}\n"%(('',',')[self.comma_last]) + self.entry_separator

**Comment by mwatts15** [comment]
> A one-liner something like this would be more pythonic:

hardly

> ```bibtex += "%s\n}\n"%(('',',')[self.comma_last]) + self.entry_separator```

not more readable

**Comment by keithbriggs** [comment]
Ok, make self.comma_last a string value '' or ',' instead of boolean, and do
    
   bibtex += "%s\n}\n"%self.comma_last + self.entry_separator

**Comment by mwatts15** [comment]
In that case, why not:
```
bibtex += self.comma_last + "\n}\n" + self.entry_separator
```

**Comment by keithbriggs** [comment]
ok

**Comment by u55** [comment]
@keithbriggs I dont' want to get into a long discussion about how to be more pythonic, but I strongly recommend that `self.comma_last` be boolean rather than a string, so that it is complementary with `self.comma_first`, and since it is only ever going to have two values. I made a PR which only adds a new one-liner:

```python
bibtex += "," if self.comma_last else ""
```
I hope this is short enough for you.
