### ISSUE TITLE
CI Environment: No Python 3.7 and Ubuntu 14.04

### ISSUE THREAD

**Issue by cao** [sciunto-org/python-bibtexparser#217]
The current build environment does not test with Python 3.7 because Travis CI does not support it (see travis-ci/travis-ci#9815).

This is not a significant issue, though tracking it for future reference.

We probably also want to bump the OS from Ubuntu 14.04 to 16.04.

**Comment by sciunto** [comment]
I opened a PR for that. Thanks for suggesting.
