### ISSUE TITLE
month name unenclosed by braces is fine for BibTeX but results in "undefinedString" error 

### ISSUE THREAD

**Issue by cpbl** [sciunto-org/python-bibtexparser#248]
The following fails with `"UndefinedString": 'jul'`:

```

import bibtexparser

ss="""
@inproceedings{tmp,
	title = {Comparison of the accuracy of {OpenStreetMap} for {Ireland} with {Google} {Maps} and {Bing} {Maps}},
	author = {Ciepluch, Blalej and Jacob, Ricky and Mooney, Peter and Winstanley, Adam},
	month = jul,
	year = {2010},
}
"""

with open('test.foo', 'w') as bibfile:
    bibfile.write(ss)


with open('test.foo') as bibtex_file:
    bib_database = bibtexparser.load(bibtex_file)

print(bib_database.entries)

```

**Comment by BrutusTT** [comment]
It might not be a bug but a hidden feature XD.

The default parser used in the load method has its parameter _common_strings_ disabled. To enable it change your script the following way:

add:

`from bibtexparser.bparser import BibTexParser`

change:
`    bib_database = bibtexparser.load(bibtex_file)`

to:
`    bib_database = bibtexparser.load(bibtex_file, BibTexParser(common_strings = True))`

**Comment by jowens** [comment]
I agree this should be the default.
