### ISSUE TITLE
Error while reading bib file

### ISSUE THREAD

**Issue by kirk86** [sciunto-org/python-bibtexparser#249]
This error was produced using bibcure which internally uses bibtexparse [here](https://github.com/bibcure/bibcure/issues/21).
In the file `bibtexexpression.py, line 10` there as function `splitlines()` operating on supposedly string `s` but after debugging `s` is neither a sting nor has a `splitlines` method.

`s` seems to be a ParseResults class
```
-> lines = s.splitlines()
(Pdb) dir(s)
['_ParseResults__lookup', '__add__', '__bool__', '__class__', '__contains__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getnewargs__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__module__', '__ne__', '__new__', '__nonzero__', '__radd__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__setattr__', '__setitem__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_asStringList', '_iteritems', '_iterkeys', '_itervalues', 'append', 'asDict', 'asList', 'asXML', 'clear', 'copy', 'dump', 'extend', 'from_dict', 'get', 'getName', 'haskeys', 'insert', 'items', 'keys', 'pop', 'pprint', 'values']

```

**Comment by MiWeiss** [comment]
I see in your referenced issue https://github.com/bibcure/bibcure/issues/21 that you resolved the problem by switching to the latest version of bibtexparse.

I'm thus closing this. Don't hesitate to ask for a re-open if I am missing something. Thanks.
