### ISSUE TITLE
strings interpolated despite interpolate_strings = None

### ISSUE THREAD

**Issue by mifads** [sciunto-org/python-bibtexparser#256]
In my bibtex file I have most journals abbreviated, e.g. acp instead of "Atmos. Chem. Physics", and these are defined at the top of my bibtex file:
```
@STRING{acp = {Atmos. Chem. Physics}}
```
I'd like to preserve the abbreviated version when using writer, but I see that they are lost as soon as I use bibtexparser. I currently try:
```
parser = BibTexParser()
parser.ignore_nonstandard_types= False # ?
parser.common_strings = True
parser.interpolate_strings = None

with open('References.bib',encoding='utf-8') as bfile:
   bb=bibtexparser.load(bfile, parser)
   testa = bb.entries_dict['Smith:2016']
```
At this stage, testa['journal'] has 'Atmos. Chem. Physics'. Can I change this to keep 'acp'?

Thanks (from a bibtexparser newbie - just discovered it today. Looks great!)

**Comment by haji-ali** [comment]
I ran into the same problem. The correct usage of this option is in the arguments of `BibTexParser`

```
parser = BibTexParser(interpolate_strings=False)
```

**Comment by mifads** [comment]
Thanks. Your suggested flag gave an error with the bibtexparser I had with my elementaryos 5 system, but now I have upgraded to the latest bibtexparser (1.1) and things are looking much better. The journal is now given as BibDataStringExpression([BibDataString('acp')], which fits the latest documentation.

**Comment by MiWeiss** [comment]
Not a bug, as confirmed by issue author
