### ISSUE TITLE
Option to export specific fields 

### ISSUE THREAD

**Issue by iburunat** [sciunto-org/python-bibtexparser#257]
I read through the docs and couldn't find how to export only specific fields. My goal is to clean my .bib file so all entries have a minimum amount of fields (e.g., author, journal, title, year). Right now my bib collection is very inconsistent having some entries long abstract while others have none, and for sharing purposes this would make finding references easier for co-authors. Thanks in advance!

**Comment by sciunto** [comment]
There is no direct way to clean the database, but once the bibtex is parsed, you can write loops to eliminate entries. Then, you can save it with the dump functions. 

Your criterion must be set between steps 2 and 3 in the tutorial: https://bibtexparser.readthedocs.io/en/master/tutorial.html

**Comment by iburunat** [comment]
Thanks for the tips. That's everything I need to get started.
