### ISSUE TITLE
bibtexparser rejects unquoted month fields

### ISSUE THREAD

**Issue by zingale** [sciunto-org/python-bibtexparser#263]
If you have a month without quotes or brackets, like those returned by the NASA ADS system, then bibtexparser complains ```bibtexparser.bibdatabase.UndefinedString: 'jul'```

The NASA ADS people say that this is allowed, pointing to this:

https://www.bibtex.com/f/month-field/

Can bibtexparser be updated to allow months in the form:
```
month = jul,
```
?

**Comment by simsong** [comment]
I have this problem also. It seems that the parser doesn't understand about the built-in, localized strings. I added this:

```
@string{jan = {Jan.}}
@string{feb = {Feb.}}
@string{aug = {Aug.}}
@string{sep = {Sept.}}
@string{oct = {Oct.}}
@string{nov = {Nov.}}
@string{dec = {Dec.}}
```

Annoyingly, the parser also removes strings that aren't used.

**Comment by guusbertens** [comment]
I have the same problem. However, by creating a parser object and setting common_strings=True, it works:
```
    p = bibtexparser.bparser.BibTexParser(common_strings=True)  # For month names.
    with open('main.bib') as f:
        db = bibtexparser.load(f, p)
```
But indeed, ideally it should parse months without needing this.

**Comment by omangin** [comment]
Indeed, the unquoted months are treated in bibtexparser as bibtex strings. At the time of writing it, it was not clear what was really part of the standard or not and the current implementation is rather strict on what it accepts. 
Please refer to https://bibtexparser.readthedocs.io/en/master/tutorial.html#using-bibtex-strings on the string support.

With the combination of the `common_string` option and the default `interpolate_strings=True` in the parser, the result is that the months are converted to their English variant. This covers the main use cases but is still quite limited.

From there on it all depends on what you intend to do with the parse data. If you intend to print the content as human-readable values, the interpolation should be fine and you can as well pass a different dictionary for these default strings (please refer to the code of the `BibTexParser` as the documentation is rather limited. If the intent is to preserve as much as possible the source data (e.g. to write it back to a bibtex file), I would suggest turning out the interpolation, that way the field values will remain a bibtex string and will be dumped in that form.

All these functionalities are rather new and not used a lot, so consider them experimental.

**Comment by simsong** [comment]
Back when I learned BibTeX, I was told that the unquoted 3-character month abbreviations were macros that were automatically localized into the current language. That was back in 1986 or 1987. It's never given me problems, but these days I'm putting all of my months in as numbers. Strangely, some people insist on:

```
   month = {3}
```

instead of:

```
   month = 3
```
