### ISSUE TITLE
Include COPYING into source distribution on PyPI

### ISSUE THREAD

**Issue by mrakitin** [sciunto-org/python-bibtexparser#270]
This conda-forge feedstock reports the `COPYING` file is missing from the distribution on PyPI: https://github.com/conda-forge/bibtexparser-feedstock/blob/223ec1f58e4dda35a04686f56910a9350f855651/recipe/meta.yaml#L39. Please update the `MANIFEST.in` to include the file. Thanks!

**Comment by mrakitin** [comment]
cc @pkgw

**Comment by sciunto** [comment]
Fixed by https://github.com/sciunto-org/python-bibtexparser/commit/10817176d890ae0f5b9353ec70ff2bb5d87adead Thanks for reporting.

**Comment by mrakitin** [comment]
Thank you!
