### ISSUE TITLE
Reading BibTex included curly braces in the titles and abstracts

### ISSUE THREAD

**Issue by Mihiretukebede** [sciunto-org/python-bibtexparser#278]
`import bibtexparser`
`with open('Included_studies.bib', encoding = "utf-8") as bibtex_file:
    included = bibtexparser.load(bibtex_file)`
`include_df =pd.DataFrame(included.entries)`

`include_df['title'].head()`

**0   {Plasma prostaglandin levels in fed and starved lean, normal and obese women}
1  {Lack of an Association Between the Presence of Tumor Necrosis Factor or Interleukin‐1 Alpha in the Blood and Weight Loss Among Elderly Patients}
2   {Effect of Weight Loss and Lifestyle Changes on Vascular Inflammatory Markers in Obese Women: A Randomized Trial}
3   {Impact of weight loss on inflammatory proteins and their association with the insulin resistance syndrome in morbidly obese patients}
4   {Expression of tumor necrosis factor (TNF)-$\alpha$ protein in the subcutaneous and visceral adipose tissue in correlation with adipocyte cell volume, serum TNF-$\alpha$, soluble serum TNF-receptor-2 concentrations and C-peptide level}
Name: title, dtype: object**

How can I remove the curly braces? 
In addition to that, does utf-8 encoding read alpha, beta, gamma, etc characters? 
Another question, does bibtexparser removes duplicated references when reading? I have 4427 references, but only 4420 are imported.

**Comment by MiWeiss** [comment]
Can you pass to me the bibtex file you are using?
