### ISSUE TITLE
getnames fails with protected names

### ISSUE THREAD

**Issue by tdegeus** [sciunto-org/python-bibtexparser#283]
True, this is very poor formatting, but I encountered an error with a protected last name:
```
>>> print(bibtexparser.customization.getnames(["{G{\'{e}}rard} {Ben Arous}"]))
["Arous}, {G{'{e}}rard} {Ben"]
```
the correct splitting would have been:
```
["Ben Arous, G{'{e}}rard Ben"]
```
Personally I don't think this case should be treated by the library, but I wanted to discuss anyway

**Comment by MiWeiss** [comment]
`Personally I don't think this case should be treated by the library`

I tend to agree, and thus close the issue for now. 

That said, wouldn't the correct splitting have been `["Ben Arous, G{'{e}}rard"]`?
