### ISSUE TITLE
Help offered

### ISSUE THREAD

**Issue by tdegeus** [sciunto-org/python-bibtexparser#284]
The readme mentions a request for maintainers. I would like to offer my help in that respect. 

In addition, I have written a wrapper around this library that:
1. Provides an entry-point with a command-line API.
2. Converts full first names to initials.
3. Tries to read doi / arxivid from other fields if either is not properly specified.
4. Applies official and officious journal abbreviations and acronyms on request.

I think that all of this features are useful for a bigger crowd (and would benefit from it), so I think it would be great to merge these features upstream here. For reference, [here is my wrapper](https://github.com/tdegeus/GooseBib), with the command line API [here](https://github.com/tdegeus/GooseBib/blob/498f1dee9d0668acd0e039f108673a78233e91e0/GooseBib/bibtex.py#L464).  

Let me know

**Comment by cromlyngames** [comment]
I second the offer of help.

**Comment by tdegeus** [comment]
Just a reminder. Your readme even says: "IMPORTANT: the library is looking for new maintainers. Please, manifest yourself if you are interested." It would be a shame if this library would be no longer actively maintained. Thereto it would be great to have a group of maintainers.

**Comment by MiWeiss** [comment]
Hi @tdegeus  and @cromlyngames 

I just started as new maintainer. Thanks for your offer, and also for the CLI idea. 
I'll need some time working through open issues and PRs. Will get back to you soon :-) 

Thanks!

**Comment by MiWeiss** [comment]
Hi @tdegeus  and @cromlyngames 

If you are still interested, started labelling issues with "need help" or "good first issue". Would be awesome if you found the time to work on one of those.

For now, I think it's best if we reduce the backlog as good as we can - and then start talking about bigger enhancements. Let me know if you're interested in participating in the discussion.

I'm closing this issue, but feel free to continue the discussion.
