### ISSUE TITLE
Unexpected logging of .bib file contents

### ISSUE THREAD

**Issue by tyarosevich** [sciunto-org/python-bibtexparser#286]
I'm having some really odd behavior with bibtexparser's internal logging functionality. I'm processing some .bib files from Science Direct's search web app:

```
import bibtexparser
import pandas as pd
from pathlib import Path
import logging
logging.basicConfig(handlers = [logging.FileHandler('logs/example.log', 'w', 'utf-8')], level=logging.DEBUG, format='%(asctime)s %(name)s %(levelname)s:%(message)s')

my_logger = logging.getLogger(__name__)
bibfolder_path = Path(path)
with open(bibfolder_path, encoding='utf-8') as bibtex_file:
    bib_database = bibtexparser.load(bibtex_file)
```

This then dumps the contents of the .bib file into the console output and then throws an unrelated UnicodeEncodeError because the logger was trying to write utf-8 to the .log file without the proper handler. After updating the handler to deal with this, the giant output was then dumped into the .log file because `bparser.py` logger is being instantiated from my namespace's `logging.basicConfig` setup. Below is a little snippet. There is one for each entry in the .bib file.

`2021-11-12 10:45:53,225 bibtexparser.bparser DEBUG: Found Entry: ['article', 'ROMERABARBERA2020102522', {'abstract': 'Paleoparasitological analysis of shaft feature sediments...`

Without a deeper understanding of how the library works, it's hard to figure out where this goes. In lieu of a stack trace I looked into it, and the debug call is on line 183 of `bparser.py`:

` self._expr.add_log_function(logger.debug)`

This leads to some logging functionality in `bibtexexpressions.py` whose purpose I don't fully understand as I'm not familiar with pyparser. 

Currently I'm just commenting out the bottom level call that causes the logging, but I thought I'd post this here as this seemed like odd behavior. Maybe it's something bizarre or dumb that I'm doing, I dunno as I'm not a python whiz. I'm happy to provide the .bib file on request.

**Comment by MiWeiss** [comment]
This looks like expected behavior? 

I'm no python logging pro either, but AFAIK, when calling `logging.basicConfig` you specify that you want to capture the `DEBUG` logs in the `logs/example.log` file, which is exactly what happens. 

Add the following line after calling `logging.basicConfig` and only warnings and errors will be logged for bparser:

`logging.getLogger('bibtexparser.bparser').setLevel(logging.WARN)`
