### ISSUE TITLE
speed check

### ISSUE THREAD

**Issue by giovannicoppola** [sciunto-org/python-bibtexparser#319]
Hello, 
My library has ~9,000 records and it takes 92 seconds to load a BibTeX export (file size: 18 MB) with the code below. 
```
with open(BIBTEX_FILE) as bibtex_file:
        bib_database = bibtexparser.bparser.BibTexParser(common_strings=True).parse_file(bibtex_file)
```

I can load the same library with more fields (file size: 91 MB) in 1.3 seconds if it is exported as JSON and read in with the code below.

```
with open(JSON_FILE, "r") as read_file:
    json_data = json.load(read_file)
```

I am wondering if I am doing something wrong, or if there is a faster way to load and convert a large BibTeX library with months defined as strings?

**Comment by MiWeiss** [comment]
Hi @giovannicoppola 

Unfortunately, you're not doing anything wrong ;-)
Indeed, bibtexparser currently is quite slow at handling medium to large inputs.

We are at the moment actively developing bibtexparser v2, which relies on a completely different parsing approach (one fast-forward pass), and which is orders of magnitude faster. 

It will take another couple of weeks until we will release the first public beta. I hope that until then, the slow parsing times are not causing you too much trouble...

**Comment by giovannicoppola** [comment]
Hello, I was wondering if you had an update on the first public beta for v2? Thanks!

**Comment by MiWeiss** [comment]
Hi @giovannicoppola 

Thanks for your continued interest. 

The v2 development branch left stealth mode a little while ago. **It is still feature-incomplete, and there's not much documentation yet**. If you just want to parse a file, with not too much magic and no writing back to files, it may already be useful to you. In that case, please get back with any feedback you have.

Branch: https://github.com/sciunto-org/python-bibtexparser/tree/v2
High-level progress tracking: #318
