### ISSUE TITLE
getnames edge-case

### ISSUE THREAD

**Issue by tdegeus** [sciunto-org/python-bibtexparser#327]
```python
>>> bibtexparser.customization.getnames(["{G{\'{e}}rard} {Ben Arous}"])
["Arous}, {G{\'{e}}rard} {Ben"]
```
whereas intended:
```python
>>> bibtexparser.customization.getnames(["{G{\'{e}}rard} {Ben Arous}"])
["{Ben Arous}, {G{\'{e}}rard}"]
```

Just to note: the current output results in illegal LaTeX.

**Comment by MiWeiss** [comment]
Thanks.

While most effort is on the dev of v2, I guess this one would be worth fixing for v1. @tdegeus would have the capacity to open a PR with a fix?
