### ISSUE TITLE
Add the equality and non-equality method between 2 bib databases

### ISSUE THREAD

**Issue by mscheltienne** [sciunto-org/python-bibtexparser#335]
Feature request: add the `__eq__` and `__ne__` methods for https://github.com/sciunto-org/python-bibtexparser/blob/a5eeffd92d431c7d9077fc2fc16894eca7c15861/bibtexparser/bibdatabase.py#L45-L151

If you want, I can open the PR.

**Comment by MiWeiss** [comment]
Sure, I guess it cannot hurt - a PR would be appreciated :-)

**Comment by MiWeiss** [comment]
closed (see #336)
