### ISSUE TITLE
entries_dict/get_entry_dict() returns stale entries_dict if called multiple times

### ISSUE THREAD

**Issue by klmmr** [sciunto-org/python-bibtexparser#345]
I wrote a script which adds new entries to a `BibDatabase`. For some checks, I need to access the `entries_dict` in each iteration. However, I found that the dict is only generated on the first call. For subsequent calls, the same dictionary will be returned, although the database might have changed in the meantime. Therefore, the dict can be outdated.

Is there a specific reason, that the `self._entries_dict` is created only on the first call of `get_entry_dict` (as caused by
https://github.com/sciunto-org/python-bibtexparser/blob/19e8dfe05490f2fb8ea1a9cc593090400eaea42a/bibtexparser/bibdatabase.py#L98)? If not, I would argue to remove the if statement, because getting an old dict is unexpected behavior.

Currently, I manually call `_make_entries_dict()` before each access to `entries_dict` to ensure a fresh dict in every iteration.

**Comment by MiWeiss** [comment]
Hi

I confirm, thanks for reporting.

Removing the if the statement has the negative side effect that calls multiple calls to the `get_entry_dict` are often unnecessary time consuming, which can be a problem for huge db. However, I guess that's an affordable price, and some smarter caching  (e.g. by checking if the hash of the list has changed) could be implemented in the future if anyone volunteers to do so.


Note: This problem applies only to v1. `v2` (under development) uses a smarter caching already.
