### ISSUE TITLE
Math latex not protected

### ISSUE THREAD

**Issue by LudovicPatey** [sciunto-org/python-bibtexparser#346]
Some titles are of the form {$\omega$ is different from $\mathbb{N}$}
When applying the unicode customization function, if will replace it to  {$∅mega$ is different from $\mathbbN$}, that is, \o is considered as a code for the empty set, and { } around N are removed because or the systematic suppression of braces.

I think we should add some functions to protect math mode. One way would be to add functions doing the following:

```
# This replaces all occurrences of $something$ by #i  and returns a list 'protection' such that the ith element is $something$
record, protection = protect_math_latex(record)

# Here, we can do whatever operations on the record, with no risk of affecting math latex

# Reverses the protection
record = unprotect_math_latex(record, protection)
```

Here is a way to do this (I added also an apply_to_keys_if_exists function which could be useful for anyone wanting to apply some custom cleaning function)

```
def apply_to_keys(record : dict, keys : list, callback) -> dict:
    """
    Apply a callback function to each key of the record
    specified in a list of keys

    :param record: the record.
    :type record: dict
    :param keys: the list of keys to which apply the callback
    :type keys: list
    :param callback: the callback function
    :returns: dict -- the modified record.
    """

    for key in keys:

        if isinstance(record[key], str):
            record[key] = callback(record[key])
        elif isinstance(record[key], dict):
            record[key] = {
                subkey: callback(value)
                for subkey, value in record[key].items()
            }
        elif isinstance(record[key], list):
            record[key] = [
                callback(value)
                for value in record[key]
            ]

    return record

def apply_to_keys_if_exists(record : dict, keys : list, callback) -> dict:
    return apply_to_keys(record, filter(lambda key : key in record.keys(), keys), callback)

def protect_math_latex(record):

    protection = list()
    
    def protect_match(m):
        index = len(protection)
        protection.append(m.group(0))
        return "#%s" % index

    def protect_string(string : str):
        return re.sub('\$[^\$]+\$', protect_match, string)

    record = apply_to_keys(record, record.keys(), protect_string)

    return record, protection


def unprotect_math_latex(record, protection):

    def unprotect_match(m):
        return protection[int(m.group(1))]

    def unprotect_string(string : str):
        return re.sub('#([0-9]+)', unprotect_match, string)     

    record = apply_to_keys(record, record.keys(), unprotect_string)

    return record
```

**Comment by tdegeus** [comment]
I have run into the same issue. Here is what I have done in the wrapper I use https://github.com/tdegeus/GooseBib/blob/a87c69c06dad12593536e33cf3041d9e89291dfb/GooseBib/reformat.py#L156

**Comment by MiWeiss** [comment]
The beta  of v2 is on the main branch and will soon be released to pypi for preview. In it, the LatexEncodingMiddleware (which replaces unicode customization of v1) has a constructor argument "keep math" which should allow to achieve exactly what this issue requires.

I doubt we will receive a PR to fix this in the (soon deprecated) v1 branch (similar problems have been reported for a long time and remained open). I thus take the liberty to close this issue.

If anyone wants to provide a fix for v1, feel free to comment and I'll happily discuss and review a PR :-)
