### ISSUE TITLE
Unclosed, escaped { in file field (edge case)

### ISSUE THREAD

**Issue by FlamingLasrSwrd** [sciunto-org/python-bibtexparser#347]
I recently encountered an error parsing a Zotero exported bibtex file. It appears to have resulted from Zotero's character limit on filenames and a pair of curly braces in the title of the paper that went unmatched when truncated. No explicit error was given. The entry just wouldn't parse.

The title of the paper is `Opportunities and challenges in the cultivation of Ashwagandha {Withania somnifera (L.) Dunal}` so the pdf file is named `Rajeswara Rao et al_2012_Opportunities and challenges in the cultivation of Ashwagandha {Withania.pdf`.

The bibtex file entry looks like this (trimmed down to reproduce the error):

```
@article{rajeswara_opportunities_2012,
  file = {Rajeswara Rao et al_2012_Opportunities and challenges in the cultivation of Ashwagandha \{Withania.pdf:/home/user/Documents/zotero/Journal of Pharmacognosy/2012/Rajeswara Rao et al_2012_Opportunities and challenges in the cultivation of Ashwagandha Withania.pdf:application/pdf}
}
```

The easiest solution is to not have curly braces in the titles. Renaming the associated file to exclude braces fixes the problem.

You can close this if you think it's a sufficiently rare case to not be an issue.

**Comment by tdegeus** [comment]
There is a matching brackets search that could help https://github.com/sciunto-org/python-bibtexparser/pull/334 . It would nice to at least emit a warning in the case of unmatching brackets.

**Comment by MiWeiss** [comment]
V2 reports unmatching brackets as failed blocks.
