### ISSUE TITLE
Parsing fails when bibtex contains duplicates

### ISSUE THREAD

**Issue by rcannood** [sciunto-org/python-bibtexparser#378]
Based on the v2 docs, it seems bibtexparser should be able to process bibtex files with duplicates. However, if a bibtex file contains duplicates, an error is produced:

```python
import bibtexparser
str = """@article{duplicate,
  author = {Duplicate, A.},
  title = {Duplicate article},
  year = {2022},
}
@article{duplicate,
  author = {Duplicate, A.},
  title = {Duplicate article},
  year = {2022},
}"""

bibtexparser.parse_string(str)
```

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "~/.local/lib/python3.10/site-packages/bibtexparser/entrypoint.py", line 93, in parse_string
        library = middleware.transform(library=library)
      File "~/.local/lib/python3.10/site-packages/bibtexparser/middlewares/interpolate.py", line 60, in transform
        for field in entry.fields:
    AttributeError: 'DuplicateEntryKeyBlock' object has no attribute 'fields'

**Comment by MiWeiss** [comment]
Thanks for the report. This is interesting; I cannot reproduce it locally, but observe the same problem when running the snippet in Colab. I will look into this.

**Comment by rcannood** [comment]
Thanks for the quick response :bow: !

**Comment by MiWeiss** [comment]
In a couple of minutes, I'll merge #379 which should fix the issue. Please re-install bibtexparser and try again.

Note: You will find the duplicate in the `library.failed_blocks` collection.
