### ISSUE TITLE
Proper persing of math mode

### ISSUE THREAD

**Issue by rudrab** [sciunto-org/python-bibtexparser#383]
Hi,
I am trying to parse doi to bibtex. My code is:
```
  def search_doi(self, doi):
    dxurl = "https://doi.org/"
    url = dxurl + doi
    if dxurl in doi:
      url = doi
    else:
      url = dxurl + doi
    print(url)
    print(doi)
    try:
      headers = {"accept": "application/x-bibtex"}
      r = requests.get(url, headers=headers, timeout=5)
      text = io.StringIO(r.text)
      del self.Parser.booklist[:]
      self.Parser.parsing_read(text)
      biblst = [list(elem) for elem in self.Parser.booklist]
      print(biblst)
```

The problem is the maths are not parsed properly. i.e.  title like "Magnetic tunneling junctions based on 2D CrI3 and CrBr3: spin-filtering effects and high tunnel magnetoresistance via energy band difference" (where CrI$_3$ and CrBr$_3$), the title is coming as "Strongly Correlated Exciton-Magnetization System for Optical Spin Pumping in {CrBr}$\\less$sub$\\greater$3$\\less$/sub$\\greater$ and {CrI}$\\less$sub$\\greater$3$\\less$/sub$\\greater$"

https://bibtexparser.readthedocs.io/en/main/bibtexparser.html?highlight=bibtexformat#id2 is not leading to anything. 

Can someone kindly help? 
I am using bibperser 1.4.0 with python 3.11.3

**Comment by MiWeiss** [comment]
> I am using bibperser 1.4.0 with python 3.11.3

Do you mean `bibtexparser` 1.4.0?  That would explain it, as math mode escaping  However, v2 supports math mode escaping. Also the docs you posted (thanks for pointing out the broken links) refer to v2. 

I suggest you try v2 (see README.md for instructions). If the problem persists, please paste a working example of the bug to this issue. Thanks

**Comment by rudrab** [comment]
I am bit confused. I have done as per instructions:
 ```
pip install --pre bibtexparser
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: bibtexparser in ./.local/lib/python3.11/site-packages (1.4.0)
Requirement already satisfied: pyparsing>=2.0.3 in /usr/lib/python3.11/site-packages (from bibtexparser) (3.0.9)

```

**Comment by rudrab** [comment]
Hi, 
I have added bibtexparser v2. 
>pip install --no-cache-dir --force-reinstall git+https://github.com/sciunto-org/python-bibtexparser@main
> Successfully installed bibtexparser-2.0.0b1 pylatexenc-2.10

Now, I am getting error in loading this part:
```
from bibtexparser import bibdatabase
from bibtexparser.bibdatabase import BibDatabase
from bibtexparser.bparser import BibTexParser
from bibtexparser.bwriter import BibTexWriter
```

which are needed in v1.4.0. 

I am getting error:

```
Traceback (most recent call last):
  File "/usr/local/bin/mkbib", line 41, in <module>
    from Mkbib import main
  File "/usr/local/lib/python3.11/site-packages/Mkbib/main.py", line 24, in <module>
    import Mkbib.getdata as getdata
  File "/usr/local/lib/python3.11/site-packages/Mkbib/getdata.py", line 21, in <module>
    import Mkbib.menu as menu
  File "/usr/local/lib/python3.11/site-packages/Mkbib/menu.py", line 17, in <module>
    import Mkbib.pybib as pybib
  File "/usr/local/lib/python3.11/site-packages/Mkbib/pybib.py", line 11, in <module>
    from bibtexparser.bparser import BibTexParser
ModuleNotFoundError: No module named 'bibtexparser.bparser'
```
Can you please help?

**Comment by MiWeiss** [comment]
Yes, v2 is not backwards compatible. You will have to adapt your code. 

I suggest you check out https://bibtexparser.readthedocs.io/en/main/quickstart.html
