### ISSUE TITLE
BlockMiddlewareTransformer does not handle `None` or collections

### ISSUE THREAD

**Issue by mlutze** [sciunto-org/python-bibtexparser#386]
According to documentation, transformers implementing `BlockMiddlewareTransformer` can return `None`, a single entry, or a collection of entries for the `transform_block` function. But returning anything other than a single entry results in a crash. The problem seems to stem from this code in `middleware.py`:

```python3
    def transform(self, library: "Library") -> "Library":
        # TODO Multiprocessing (only for large library and if allow_multi..)
        blocks = [self.transform_block(b, library) for b in library.blocks]
        return Library(blocks=blocks)
```

It doesn't handle cases where `transform_block` does not return an entry.

**Comment by MiWeiss** [comment]
That's right, that's a bug.

Would you be able to open a PR with a fix, alongside some tests to make sure we don't break that again in the future?
