### ISSUE TITLE
FieldMiddleware

### ISSUE THREAD

**Issue by mlutze** [sciunto-org/python-bibtexparser#388]
I have several middlewares  that are interested in looking at fields independently. I wonder whether it would be useful to add to the library.

Something like this:

```python3

class FieldMiddleware(BlockMiddleware, abc.ABC):
    def transform_entry(entry, library):
        fields = [self._transform_field(field, entry, library) for field in entry.fields]
        return Entry(
            entry_type=entry.entry_type,
            key=entry.key,
            fields=fields
        )

    @abc.abstractmethod
    def transform_field(field, entry, library):
        pass
```

(Though maybe with special handling for `None` and collections returned from `transform_field`)

**Comment by MiWeiss** [comment]
Thanks for the proposition. There's a few details that would have to be cleared before implementing such a layer. 

The first one coming to my mind: What are we going to do with non-entry blocks? Blocks like @string or @preamble have a single field-like value...

**Comment by mlutze** [comment]
Good point, I had not considered that. Perhaps we can have a `transform_entry_field` and `transform_string_field` etc. for these cases?

**Comment by MiWeiss** [comment]
Hi

Excuse my very late reply. I had to think about that for a bit, but then forgot to post my thoughts :-P

With what we discussed above, it seems to me as if this would add quite some new technical depth into the code without actually that much useful abstraction for the end user implementing their own middleware. Maybe this would become more useful if we already integrated extended logic, such as ways to filter fields etc, but I am not sure how big the demand for such a middleware would actually be. I'd thus tend towards not committing this into the repo at the moment (once it's committed it will be very hard to change it or get rid of it, as some users may depend on it).  Do you agree or is there anything I am missing?

Note: The existing middlewares already have some potential in them (e.g. parallel processing of independent blocks in Blockmiddleware). For fields, I currently see no further such advantage.

**Comment by mlutze** [comment]
I think that's a fair assessment. I'll try implementing it for my own project, and if it seems indispensable for some reason, I'll report back.

**Comment by MiWeiss** [comment]
I'll close this for now, then. Thanks!
