### ISSUE TITLE
BibTexWriter sorting strategy for crossref

### ISSUE THREAD

**Issue by JensNevens** [sciunto-org/python-bibtexparser#389]
I am using the bibfish package to automatically create a local bibtex file from a central bibtex database based on the citations found in a latex manuscript. The bibfish package relies on the BibDatabase of this package. However, bibfish does not support the use of crossref fields (see https://github.com/jwcarr/bibfish/issues/7). In an attempt to add this feature, I wanted to use a custom instance of the BibTexWriter. Particularly, in order to use crossref correctly, the cross referenced entries should be placed at the bottom of the bib file. Thus, I am trying to sort the bibtex entries as follows:

- regular bibtex entries, sorted alphabetically on the bibtex key
- cross referenced entries, sorted alphabetically on the bibtex key

Is there any way to customise the BibTexWriter in order to achieve this?

**Comment by MiWeiss** [comment]
Hi @JensNevens 

Thanks for your question. I assuming it refers to `bibtexparser v1`.

Achieving your desired behavior should be quite easy though: If guess that if you replace the fields ` self.entries` and `self._entries_dict` with ones containing your desired order you should be exactly where you want to be. Just be aware that this is not a documented way to use the library and may break in later `v1` versions (it's not applicable to `v2` anyways), but this is rather unlikely given that not much changes other than bugfixes are made on `v1` anymore. Still, it is at your own risk...

Another note: The hack above may not work if you later export/write the BibDatabase, in which case a new sorting behavior may be used.

Yet another note: This is easily achieved with a custom `LibraryMiddelware` in `v2`. I am just saying this in case bibfish was planning on upgrading some day (I hope I'll find the time to release a beta version of `v2` to pypi soon).

Hope this helps. 

Best, 
Michael

**Comment by MiWeiss** [comment]
Closing this as answered, feel free to continue the thread and tag me if there's still open issues.
