### ISSUE TITLE
Allow addition of duplicate entries

### ISSUE THREAD

**Issue by claell** [sciunto-org/python-bibtexparser#402]
**Is your feature request related to a problem? Please describe.**
In addition to #401, one more thing that I'd like to request. I need to add duplicate entries sometimes. Currently, that does seem to be always silently avoided.

**Describe the solution you'd like**
Add an argument to the `add()` function of the library that allows to add duplicate entries, or maybe a general property for the library (?).

**Use cases**
I want to replicate some export behavior of different sites. There, it can be possible that duplicate entries will be generated for the export. So to identically replicate such exports (even if not good quality), I need this functionality.

**Describe alternatives you've considered**
Not using this library for that purpose.

**Remaining Questions (Optional)**
Please tick all that apply:

- [ ] I would be willing to to contribute a PR to fix this issue.
- [ ] This issue is a blocker, I'd be greatful for an early fix.

**Comment by MiWeiss** [comment]
Unfortunately, we cannot allow multiple entries with the same key in the same library instance. 

The reason for that is that we allow to access entries by key using `library.entries_dict`, which is one of the most important methods, especially for anyone migrating from v1. Having multiple entries with the same key in the library would result to undefined/unexpected behavior here. I thus deliberately decided against allowing such duplicates.

**Workarounds:** Your usecase, while certaintly valid, appears to be quite rare and I guess using a workaround would be acceptable. This could e.g. by creating a middleware which maps duplicate key entries to regular entries with a "DUPLICATEKEY" suffix added to the key. You could then write the library to bibtex in memory, followed by a simple `str.replace("DUPLICATEKEY","")`.

**Comment by claell** [comment]
Alright, thanks for providing a workaround. Possibly, one could also add another parameter to the write functions supporting this out of the box (or this won't be needed, depending, how #400 will be dealt with).
