### ISSUE TITLE
docs maybe need updating

### ISSUE THREAD

**Issue by lbugnon** [sciunto-org/python-bibtexparser#410]
if you do the following, parse_string function is not found 

!pip install --no-cache-dir --force-reinstall git+https://github.com/sciunto-org/python-bibtexparser@main
import bibtexparser
library = bibtexparser.parse_string("asd")

**Comment by MiWeiss** [comment]
I have just tried it right now and it works without any problems.

![image](https://github.com/sciunto-org/python-bibtexparser/assets/4815944/61a83e69-4c6e-44fa-81bf-dae3ccca614d)

I recommend you check if installation is successful by running `!pip show bibtexparser`, making sure that you indeed have the latest version (v2.0.0b3):

![image](https://github.com/sciunto-org/python-bibtexparser/assets/4815944/6dcf7f77-d700-41ee-b05a-64ac6e60d86a)

I am closing this for now, but please feel free to continue commenting if you figure out additional info.
