### ISSUE TITLE
Parsing math mode

### ISSUE THREAD

**Issue by rudrab** [sciunto-org/python-bibtexparser#414]
I am writing this as connected to #383.
I have managed to move to bibtexparser-v2. But, mathmode is still not parsed properly (am I missing some middleware?)
Here is my mwe:
```
import bibtexparser
import requests

url = "http://dx.doi.org/10.1103/PhysRevB.90.014402"
headers = {"accept": "application/x-bibtex; charset=utf-8"}
r = requests.get(url, headers=headers, timeout=5)
text = r.text  # io.StringIO(r.text)
#  print(text)
db = bibtexparser.parse_string(text)
fields = db.entries[0].fields_dict
print(fields)
```

This code is returning the fields as (see the `title` field): 

`{'doi': Field(key=`doi`, value=`10.1103/physrevb.90.014402`, start_line=1), 'url': Field(key=`url`, value=`https://doi.org/10.1103%2Fphysrevb.90.014402`, start_line=2), 'year': Field(key=`year`, value=`2014`, start_line=3), 'month': Field(key=`month`, value=`jul`, start_line=4), 'publisher': Field(key=`publisher`, value=`American Physical Society ({APS})`, start_line=5), 'volume': Field(key=`volume`, value=`90`, start_line=6), 'number': Field(key=`number`, value=`1`, start_line=7), 'author': Field(key=`author`, value=`Alexander Edström and Jonathan Chico and Adam Jakobsson and Anders Bergman and Jan Rusz`, start_line=8), 'title': Field(key=`title`, value=`Electronic structure and magnetic properties of$\less$mml:math xmlns:mml="http://www.w3.org/1998/Math/{MathML}"$\greater$$\less$mml:mrow$\greater$$\less$mml:mi$\greater$L$\less$/mml:mi$\greater$$\less$mml:msub$\greater$$\less$mml:mn$\greater$1$\less$/mml:mn$\greater$$\less$mml:mn$\greater$0$\less$/mml:mn$\greater$$\less$/mml:msub$\greater$$\less$/mml:mrow$\greater$$\less$/mml:math$\greater$binary alloys`, start_line=9), 'journal': Field(key=`journal`, value=`Physical Review B`, start_line=10)}`

This is because the bibtex I get from the urllib3 is also in HTML. 

Can the title field be in proper LaTeX encoding? Ihave tried with 
```
layers = [
    m.LatexEncodingMiddleware(keep_math=True,
                              enclose_urls=True,
                              allow_inplace_modification=True),
    m.MonthIntMiddleware(True)
]
db = bibtexparser.parse_string(text, append_middleware=layers)
```

**Comment by MiWeiss** [comment]
Hi @rudrab 

Thanks for opening the issue. I am afraid I did not have the time to look at your snippet in detail, thus do not hesitate to tell my if my answer misses its target ;-)

I am afraid I may have misunderstood (or misjudged) your question in your previous issue. Are you trying to parse math-mode into "regular, escaping-free" text? If so, I do not think this is possible in general:

Example: Assume we wanted to parse the string `$\sqrt{\frac{1}{2_x}}$`, i.e., $\sqrt{\frac{1}{2_x}}$. I don't think this could reasonably be represented as plain, human-readable text (i.e., without escaping etc.), right? Of course, the more complicated the math-mode-encoded formula gets, the less likely we can represent it in plain text.

There's two approaches which seems best suited to handle your request:
- Approach [pylatexenc](https://github.com/phfaist/pylatexenc), the project which we use internally for latex decoding and address the issue there. This is where any change would have to happen anyways.
- Write your own custom middleware to handle simple cases which can be represented as text, such as replacing `$\leq$` with `<=`. While I do not think we can maintain such a middleware as part of bibtexparser, I would happily link to your middleware in our docs, if you created one.

I hope this helps (somewhat). I'll leave this issue open for a bit in case there's something I missed.
