### ISSUE TITLE
Unable to import bparser

### ISSUE THREAD

**Issue by lepmik** [sciunto-org/python-bibtexparser#415]
**Describe the bug**
Unable to import bparser

**Reproducing**

Version: `bibtexparser 2.0.0b3` installed with `pip install --pre bibtexparser`
Python 3.9.18 (main, Sep 11 2023, 08:25:10) 
[Clang 14.0.6 ] :: Anaconda, Inc. on darwin
conda version : 23.5.2
conda-build version : 3.25.0
macOS 14.0
Apple M2 Pro

Code:
```python
import bibtexparser
from bibtexparser.bparser import BibTexParser

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'bibtexparser.bparser'
```

- [ ] I would be willing to to contribute a PR to fix this issue.
- [x] This issue is a blocker, I'd be greatful for an early fix.

**Comment by MiWeiss** [comment]
Hi 

The code you are trying to run corresponds to bibtexparser `v1`. However, by specifying `--pre` in the pip install command, you are downloading the `v2-beta` version. The two major versions have completely different APIs.

Installing using `pip install bibtexparser~=1.0` or alternatively changing your code as described in the [v2 docs](https://bibtexparser.readthedocs.io/en/main/migrate.html#differences-between-v1-and-v2) should do the trick.
