### ISSUE TITLE
Set position of field insertion (or in general ordering of fields for export)

### ISSUE THREAD

**Issue by claell** [sciunto-org/python-bibtexparser#426]
**Is your feature request related to a problem? Please describe.**
Usually, one prefers a standardized order for the fields of an entry. Currently, the fields seem to be ordered by addition to the entry? That is often not really consistent, at least in some cases.

**Describe the solution you'd like**
Is there a way to specify where to insert a field to an entry? Or to specify the field order (or enforce some default order) for export to ensure consistency of all entries?

**Use cases**
Avoid reordering of fields when opening with other applications like JabRef. Instead just export in the default order. Helps when doing versioning of .bib files with git, for example.

**Describe alternatives you've considered**
Not sure. Manually doing this?

**Remaining Questions (Optional)**
Please tick all that apply:

- [ ] I would be willing to to contribute a PR to fix this issue.
- [ ] This issue is a blocker, I'd be greatful for an early fix.

**Comment by claell** [comment]
This might already be possible, so maybe not a feature request, but just a question. I'd be happy to know a way to do this!

**Comment by MiWeiss** [comment]
Hi @claell 

Have you considered using either of the following middlewares:

- `bibtexparser.middlewares.SortFieldsAlphabeticallyMiddleware`
- `bibtexparser.middlewares.SortFieldsCustomMiddleware`

If they solve your issue, I don't blame you for not having found them. Middleware documentation is still quite lousy; something we should have a look at.

**Comment by claell** [comment]
No, didn't know these. Thanks for your quick reply, looks exactly like what I was looking for! How can I use these middlewares? Is there some example that can be referenced?

**Comment by MiWeiss** [comment]
Does this help: [https://bibtexparser.readthedocs.io/en/main/customize.html#middleware-layers](https://bibtexparser.readthedocs.io/en/main/customize.html#middleware-layers)

**Comment by claell** [comment]
Yes, exactly. I think that was what I had back in my head, thanks for the reference!

**Comment by MiWeiss** [comment]
Great. 

Please dont hesitate to open a PR if you see anything in the docs that need to be changed.
