### ISSUE TITLE
"comment" lines without leading @ breaks parser

### ISSUE THREAD

**Issue by auxym** [sciunto-org/python-bibtexparser#43]
I'm not sure if such lines conform to bibtex syntax, but they are found in standard packages. See, for example, [IEEEabrv.bib](http://www.tex.ac.uk/CTAN/biblio/bibtex/contrib/IEEEtran/IEEEabrv.bib).

Some minimal examples:

```
@STRING{Foo = "bar"}
This is a comment
This is a second comment.
```

This returns the incorrect dictionary entry `OrderedDict([('foo', 'bar"} This is a comment This is a second comment.')])`

```
@STRING{Foo = "bar"}
This is a comment
STRING{Baz = "This should be interpreted as comment."}
```

This raises an exception when parsed.

I had a quick look at the parser code. Maybe, instead of using a new `@` line as the record delimiter, it should use the braces?

As a workaround, I'm removing all lines not starting with `@` before parsing the aforementioned IEEEabrv.bib fil, but this only works because this particular file only has one-liners.

**Comment by sciunto** [comment]
Fixed in master. Thanks.
