### ISSUE TITLE
Format names `last, first`

### ISSUE THREAD

**Issue by tdegeus** [sciunto-org/python-bibtexparser#438]
**Is your feature request related to a problem? Please describe.**
I would like to format names in the output as `last, first`

**Describe the solution you'd like**
```python
bibtex_str = """
@ARTICLE{Cesar2013,
  author = {Jean César and T. W. J. de Geus},
  title = {An amazing title},
  year = {2013},
  volume = {12},
  pages = {12--23},
  journal = {Nice Journal}
}
"""

import bibtexparser
import bibtexparser.middlewares as m

layers = [
    m.SeparateCoAuthors(True),
    m.SplitNameParts(True)
]
library = bibtexparser.parse_string(bibtex_str, append_middleware=layers)

layers = [
    m.MergeNameParts(True),
    m.FormatNames("{last}, {first}"), # to be discussed!
    m.MergeCoAuthors(True)
]
print(bibtexparser.write_string(library, prepend_middleware=layers))
```
should then print 
```bib
@ARTICLE{Cesar2013,
  author = {César, J. and de Geus, T. W. J.},
  title = {An amazing title},
  year = {2013},
  volume = {12},
  pages = {12--23},
  journal = {Nice Journal}
}
```

**Use cases**
In my experience, certain styles need this. 

**Describe alternatives you've considered**
-

**Remaining Questions (Optional)**
Please tick all that apply:

- [x] I would be willing to to contribute a PR to fix this issue.
- [x] This issue is a blocker, I'd be greatful for an early fix.

**Comment by tdegeus** [comment]
Seems addressed here https://github.com/sciunto-org/python-bibtexparser/pull/422

**Comment by MiWeiss** [comment]
> Seems addressed here https://github.com/sciunto-org/python-bibtexparser/pull/422 and discussed in https://github.com/sciunto-org/python-bibtexparser/issues/421

As these are merged and closed now, I am also closing this issue. If anything remains unsolved for your usecase, we may be able to address it as part of #439 (which is conceptionally related), or in a new issue, as you prefer.
