### ISSUE TITLE
How to replace bp.bparser.BibTexParser() ?

### ISSUE THREAD

**Issue by tillea** [sciunto-org/python-bibtexparser#451]
**Describe the bug**
I'd like to fix a [bug in the Debian package qiime](https://bugs.debian.org/1060965) which fails its CI test due to [this line](https://salsa.debian.org/med-team/qiime/-/blob/master/qiime2/core/cite.py?ref_type=heads#L26)

    parser = bp.bparser.BibTexParser()

I `grep`ed through the source code of python-bibtexparser and can't find it any more in 2.0.0b* while it was at least available in version 1.1.0 (which worked nicely with the CI test of `qiime`. 

**Reproducing**
Its not really a bug if you change the API but it would be great to mention those changes in your changelog to inform users how to fix their code to adapt it to the new version.

# Paste a minimal code example to reproduce the issue here

    import bibtexparser as bp
    parser = bp.bparser.BibTexParser()
    
            parser = bp.bparser.BibTexParser()
                 ^^^^^^^^^^
    AttributeError: module 'bibtexparser' has no attribute 'bparser'

This is the case for version 2.0.0b5 of bibtexparser

**Workaround**

Seems reverting to some 1.x version (definitely 1.1.0 which was packaged in Debian before) makes the code above valid code.

- [ ] I would be willing to contribute a PR to fix this issue.
- [x] This issue is a blocker, I'd be grateful for an early fix.

I consider some proper documentation of the API change a proper fix.  I'd happily create a patch for `qiime` in Debian and will propagate it to upstream.

**Comment by MiWeiss** [comment]
Hi

I am surprised that you are actually installing any `2.0.0b*` version, which are beta version with certainly a bunch of relevant bugs and future small, but breaking api changes expected.

Thus, your "workaround" is probably the thing you want to do. Note: 1.4.1 is still listed as last stable version of bibtexparser on pypi: https://pypi.org/search/?q=bibtexparser  Going to any 2.x version requires to deliberately install a pre-release, e.g. by calling `pip install bibtexparser --pre`.

Regarding the changelog:

> it would be great to mention those changes in your changelog to inform users how to fix their code to adapt it to the new version.

The changelog literally sais: 

![image](https://github.com/sciunto-org/python-bibtexparser/assets/4815944/43ee9657-10f4-4c99-8197-6645dc6b1e4c)

Certainly, before releasing a stable 2.x version, the documentation will continue to grow.

**Comment by tillea** [comment]
Thanks a lot for the clarification.  Just to clarify:  It was not me who decided to use a beta version.  Some other maintainer decided to grab the latest tag at some point in time.  Seems we need to revert this change to the latest stable version.
