### ISSUE TITLE
Discussion: closer `dict` mimicking `Entry`

### ISSUE THREAD

**Issue by tdegeus** [sciunto-org/python-bibtexparser#461]
I think that it would be a good idea to have the API of `Entry` mimic `dict`. The advantages are:

* Intuitive API, as everyone's familiar with `dict`
* Simpler tests middleware implementations: for many purposes, one can just call the `transform_entry` method with a `dict` when testing.

Indeed, `Entry` acts in several ways similar to a `dict`

https://github.com/sciunto-org/python-bibtexparser/blob/57bdc8effe0d6fe418b577cf9ea0b75911a219a5/bibtexparser/model.py#L317

My proposal is therefore to rename

https://github.com/sciunto-org/python-bibtexparser/blob/57bdc8effe0d6fe418b577cf9ea0b75911a219a5/bibtexparser/model.py#L307

```python
def pop(self, key: str, default: None) -> Optional[Field]: 
```

I understand that there are probably good reasons to have chosen `pop_field`. However, I wanted this discussion out there, as I do think that making this set would encourage middleware development. (In addition to now being the time to still make changes)

**Comment by MiWeiss** [comment]
> I understand that there are probably good reasons to have chosen `pop_field`

Thanks for your generous assumptions ;-) I don't recall the reason, hence it can't be a good one.

In short, I like the proposition, but as you may have noticed I am currently extremely short on time and won't even be able to fix that immediately. If you fancy opening a PR I'd be happy to merge that.
