### ISSUE TITLE
Apply style using pre-commit

### ISSUE THREAD

**Issue by tdegeus** [sciunto-org/python-bibtexparser#464]
To expedite applying formatting, one could consider `pre-commit` instead of manual configuring the CI. 

https://github.com/sciunto-org/python-bibtexparser/blob/57bdc8effe0d6fe418b577cf9ea0b75911a219a5/.github/workflows/linting_and_unittests.yml#L22

See e.g.

https://github.com/tdegeus/texplain/blob/main/.pre-commit-config.yaml
https://github.com/tdegeus/texplain/blob/main/.github/workflows/pre-commit.yml

**Comment by MiWeiss** [comment]
Well, I am not a big fan of pre-commit. I found it to be slow and buggy. But then again the last time I gave it a try must be years ago. Thus, feel free to open a PR: No one is forced to use pre-commit locally, but it sure makes stuff nicer.
