### ISSUE TITLE
Question: sorting blocks by specific field values

### ISSUE THREAD

**Issue by oborin1** [sciunto-org/python-bibtexparser#478]
**Is your feature request related to a problem? Please describe.**
I want to sort my bibtex blocks using values of a specific field, e.g., year. Is it already possible with SortBlocksByTypeAndKeyMiddleware()?

**Describe the solution you'd like**
Unsorted bibtex file --> Sorted bibtex file with blocks arranged in ascending order, e.g., by year.

**Use cases**
1. Merge transliterated and originally Latin bibliographies having author-year citation mode as part of translation.
2. Sort an untidy bibliography.

**Describe alternatives you've considered**
None.

**Remaining Questions (Optional)**
- [x ] I would be willing to contribute a PR to fix this issue.
- [ ] This issue is a blocker, I'd be grateful for an early fix.

**Comment by MiWeiss** [comment]
Thanks for your question. Which version of `bibtexparser` do you use? `v1.0.0x` or `v1.4.x`?

**Comment by oborin1** [comment]
Thank you for your prompt answer. I'm currently migrating from v1.4.x to v2.0.0x.

**Comment by MiWeiss** [comment]
Great!

The `SortBlocksByTypeAndKeyMiddleware` is not exactly what you want, as it implements a predefined order based on the block types (entry, string, ...) and the keys of the blocks.

Instead you'd want to create your own custom middleware extending `LibraryMiddleware` using your desired logic. Here, you may want to take the [SortBlocksByTypeAndKeyMiddleware](https://github.com/sciunto-org/python-bibtexparser/blob/main/bibtexparser/middlewares/sorting_blocks.py) Implementation as an example.

In the long run, we'll certainly want to expose a simple way to achieve this (e.g. by exposing a dedicated abstract class for sorting, or a class which takes a comparator as constuctor argument), but as of now, this is not yet supported.

**Comment by MiWeiss** [comment]
I created https://github.com/sciunto-org/python-bibtexparser/issues/480 to track the progress of the above mentioned improvements.

**Comment by MiWeiss** [comment]
closed as answered and inactive
