### ISSUE TITLE
does this package provide CURD function?

### ISSUE THREAD

**Issue by eastGrass** [sciunto-org/python-bibtexparser#482]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Use cases**
Please describe - from a very far perspective - the use cases which this feature allow, which are not or only suboptimally supported without the current feature.

**Describe alternatives you've considered**

**Remaining Questions (Optional)**
Please tick all that apply:

- [ ] I would be willing to contribute a PR to fix this issue.
- [ ] This issue is a blocker, I'd be grateful for an early fix.

**Comment by eastGrass** [comment]
create a new library from old one
R: this is ok
for example, I want to select some bibitem from library, then create a new library

**Comment by MiWeiss** [comment]
I honestly do not understand your question?

What library version are you referring to? Do you mean CRUD? 

Please re-open a new issue and fill out the feature request template, instead of leaving just the defaults
