### ISSUE TITLE
Suggestion: Set logging name instead of root

### ISSUE THREAD

**Issue by R0k1e** [sciunto-org/python-bibtexparser#494]
**Is your feature request related to a problem? Please describe.**
When I use this wonderful work to parse .bib file and meet duplicate block, hundreds of warning log will appear in the terminal which I don't wish to watch but don't have easy way to turn it off.

**Describe the solution you'd like**
Set name to logger instead of "root".

**Use cases**
Parse .bib file with duplicate blocks

- [ ] I would be willing to contribute a PR to fix this issue.
- [ ] This issue is a blocker, I'd be grateful for an early fix.

**Comment by MiWeiss** [comment]
Yes, this absolutely has to be done :-) Thanks for opening the ticket

Would you bother opening a PR? I am currently not available to do any change myself, but would gladly review and merge this (likly small) change

**Comment by MiWeiss** [comment]
Ah, wait a second :-D

This has already been done, it's just not yet released: 
https://github.com/sciunto-org/python-bibtexparser/pull/483

I'll release soon

**Comment by MiWeiss** [comment]
`v2.0.0b8` is now released! Thanks for opening the issue.
