### ISSUE TITLE
Release 1.4.2 github sources are actually 2.0.0b7

### ISSUE THREAD

**Issue by APN-Pucky** [sciunto-org/python-bibtexparser#496]
The `__init__` file has 2.0.0b7 set... in the source file of the 1.4.2 release.

https://github.com/sciunto-org/python-bibtexparser/archive/refs/tags/v1.4.2.zip

However, the pypi release seems to actually be 1.4.2.

See-also: https://bugs.gentoo.org/946634

**Comment by MiWeiss** [comment]
What a mess? What have I done? And how is it possible that it took sooooo long for anyone to notice? xD

**Comment by MiWeiss** [comment]
I'll (hopefully) release 1.4.3 as a fix later today.

Please don't hesitate to aggressively ping me should I forget ;-)

**Comment by MiWeiss** [comment]
Ok, so. Turns out - as you suspected - that on pypi the correct sources were released. "Only" the github tag was wrong. 

I decided to "fix" the tag to the correct commit to create alignment with pypi (which is used far more often). I am aware of the consequences this may have (e.g. wrong cached versions) but hope that they will not overly manifest.

Does this solution work for you? Otherwise I'll still release an identical 1.4.3

**Comment by APN-Pucky** [comment]
I am sorry, but I think you "verschlimmbessered" things: 
![2024-12-19_10-41-35_Releases](https://github.com/user-attachments/assets/b4d31cbe-0c20-4fdf-b6f1-6607c710bd15)

**Comment by MiWeiss** [comment]
oh my... 

next try:

![image](https://github.com/user-attachments/assets/00b69b45-881c-4a81-b403-1b9924a756da)

**Comment by mgorny** [comment]
Could you make it 1.4.3 instead? Given that at least we fell into the trap, a new release will make sure that everyone gets a notification about it and updates their downstream packages / projects.

**Comment by MiWeiss** [comment]
Of course. 

Thanks for your reports @APN-Pucky  and @mgorny and for being kind despite the collosal mess 😄 

I hope with 1.4.3 everything is fine now.



---

in other news: i should definitely find the courage to release v2 from it's beta-chains. On that branch, everything is nicely automated, thus significantly reducing the probability that I mess stuff up :-P

**Comment by mgorny** [comment]
Thanks!
