### ISSUE TITLE
Relative imports

### ISSUE THREAD

**Issue by sjpfenninger** [sciunto-org/python-bibtexparser#59]
I've embedded this library in a plugin for the Sublime Text editor, see https://github.com/sjpfenninger/citebibtex. The module therefore isn't properly installed, and I needed to change some of your import statements from absolute to relative. For example, in bparser.py, I changed

`from bibtexparser.bibdatabase import BibDatabase`

to

`from .bibdatabase import BibDatabase`

Is there a reason to have absolute imports? I think changing these to relative will have no adverse effects in any case.

**Comment by sciunto** [comment]
There is no reason, you can submit a PR :)
