### ISSUE TITLE
Unknown entry types

### ISSUE THREAD

**Issue by hetsch** [sciunto-org/python-bibtexparser#65]
Hi,

first thank you for this library! 
Have you ever considered integrating the biblatex entry types `@collection`, `@report` or `@thesis`? I'm currently exporting my biblatex file from Zotero and get many errors like:

    Entry type collection not standard. Not considered.
    Entry type report not standard. Not considered.
    Entry type thesis not standard. Not considered.

Would it be easy to integrate those types into the library or would it be too much work? `@collection` seems to be a pretty often used one ...

Thank you!

**Comment by sciunto** [comment]
You can have a look at this part of the documentation: https://bibtexparser.readthedocs.org/en/latest/bibtexparser.html#bparser.BibTexParser
The option ignore_nonstandard_types should help you.

I'm closing but if you have any problem or suggestion, feel free to reopen.

**Comment by hetsch** [comment]
Thank's, I'm allright with that hint. Works fine!

**Comment by anntzer** [comment]
Note that the doc entry you link to suggests that one can pass `ignore_nonstandard_types` as kwarg to the constructor, but this fails as of the latest released version (0.6.2):
```
In [2]: BibTexParser(ignore_nonstandard_types=False)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-15d3fbb3ce7e> in <module>()
----> 1 BibTexParser(ignore_nonstandard_types=False)

TypeError: __init__() got an unexpected keyword argument 'ignore_nonstandard_types'
```

It does work as of master though.  Any chance for a new release?  Thanks in advance.

**Comment by sciunto** [comment]
@anntzer The project is looking for maintainers. I do not have enough time to maintain it anymore, unfortunately.

**Comment by anntzer** [comment]
You may want to leave a note to that effect in the README, then.

**Comment by sciunto** [comment]
I know, I have to do it.
