### ISSUE TITLE
list of dicts to bibtex object?

### ISSUE THREAD

**Issue by paultopia** [sciunto-org/python-bibtexparser#68]
Hi there, 

Perchance, do you have a direct way in the module to dump a straight list of dicts to a bibtex-formatted string directly, or first convert them into a bibtex object?  Looking at the API docs, it looks like there's a method to get strings into bibtex objects, which include the data as lists of dicts, and bibtex objects to bibtex-formatted strings, but no obvious way to get a list of dicts programmatically created to output as a bibtex formatted string...

**Comment by sciunto** [comment]
Hi,

There is no function to do that for now, but it should not be too difficult to implement. The most triky part is to check the dict is valid (correct entries...)

**Comment by paultopia** [comment]
right-on.  Hmm... maybe I'll try and write one when I find the time...

**Comment by sciunto** [comment]
I close this. Feel free to reopen if needed.
