### ISSUE TITLE
One-line bibtex records are not supported

### ISSUE THREAD

**Issue by wetneb** [sciunto-org/python-bibtexparser#69]
Some sources (such as ORCiD) return bibtex records with no newlines between the fields:
<pre>
@article { cortadella1993,title = {Division with speculation of quotient digits},journal = {Proceedings - Symposium on Computer Arithmetic},year = {1993},pages = {87-94},author = {Cortadella, Jordi and Lang, Tomas}}
</pre>
It seems that the parser does not support this format.

**Comment by stuz5000** [comment]
I've also run into this. Is making python-bibtexparser unusable for me. Was there a workaround (such as adding line breaks)?

**Comment by sciunto** [comment]
It's not supported and the way the parser is written doesn't make this task easy to tackle nicely.
I hope to be able to work on #64 in few months.

**Comment by sciunto** [comment]
TODO: check if #64 solves this bug.

**Comment by sciunto** [comment]
Fixed by #64.
