### ISSUE TITLE
"from bibtexparser import *" fails

### ISSUE THREAD

**Issue by wetneb** [sciunto-org/python-bibtexparser#70]
Is this behaviour normal or desired?
<pre>
>>> from bibtexparser import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'dumpbparser'
>>> import bibtexparser
>>> 
</pre>

**Comment by sciunto** [comment]
Fixed in 0.6.2.
