### ISSUE TITLE
parser (or writer) fails on some inputs

### ISSUE THREAD

**Issue by keithbriggs** [sciunto-org/python-bibtexparser#85]
When I feed this entry:

@book{Baehrens:Panegyrici,
  title=    "XII panegyrici Latini: post Aemilium Baehrensium iterum recensuit Guilielmus Baehrens",
  editor=   "W. Baehrens and E. Baehrens",
  year=     1911,
  publisher="B. G. Teubner",
  address=  "Lipsiae [Leipzig]",
  keywords= {primary_source},
}

through this code:

import bibtexparser
from bibtexparser.bparser import BibTexParser
from bibtexparser.bwriter import BibTexWriter
from bibtexparser.customization import homogeneize_latex_encoding

if __name__=='__main__':
  parser=BibTexParser()
  writer=BibTexWriter()
  parser.customization=homogeneize_latex_encoding
  with open('../bibtex/primary_sources.bib') as bibtex_file:
    bib_database=bibtexparser.load(bibtex_file,parser=parser)
    print(writer.write(bib_database))

I get:

@book{Baehrens:Panegyrici,
 address = {},
 editor = {},
 isbn = {},
 keyword = {primary\_source},
 publisher = {},
 series = {},
 shorthand = {},
 sortname = {},
 title = {},
 volume = {},
 year = {}
}

Why does it lose all the field values except one, and why does it invent non-existent fields?

**Comment by sciunto** [comment]
```



# Creating test file
bibtex = """@book{Baehrens:Panegyrici,
title= "XII panegyrici Latini: post Aemilium Baehrensium iterum recensuit Guilielmus Baehrens",
editor= "W. Baehrens and E. Baehrens",
year= 1911,
publisher="B. G. Teubner",
address= "Lipsiae [Leipzig]",
keywords= {primary_source},
}
"""
with open('/tmp/bibtex.bib', 'w') as bibfile:
    bibfile.write(bibtex)

# Import the package without installing it.
import sys
import os
btp_path = os.path.join('.', 'python-bibtexparser') 
sys.path.append(btp_path)
import bibtexparser
from bibtexparser.bparser import BibTexParser
from bibtexparser.bwriter import BibTexWriter
from bibtexparser.customization import homogenize_latex_encoding


# Load bibtex file and get its content as string.
with open('/tmp/bibtex.bib') as bibtex_file:
    bibtex_str = bibtex_file.read()

# Parse and show the string.
parser=BibTexParser()
writer=BibTexWriter()
parser.customization=homogenize_latex_encoding
bib_database = bibtexparser.loads(bibtex_str, parser=parser)
print(writer.write(bib_database))

```


gives me (with master)
```
@book{Baehrens:Panegyrici,
 address = {Lipsiae [Leipzig]},
 editor = {W. Baehrens and E. Baehrens},
 keywords = {primary\_source},
 publisher = {B. G. Teubner},
 title = {X{I}I panegyrici {L}atini: post {A}emilium {B}aehrensium iterum recensuit {G}uilielmus {B}aehrens},
 year = {1911}
}
```
