### ISSUE TITLE
Brackets enclosing values (i. e. {{Institutional Author}}) are removed

### ISSUE THREAD

**Issue by bluebirch** [sciunto-org/python-bibtexparser#97]
The parser does a little bit too much cleanup. Entire values enclosed in brackets are stripped of the enclosing brackets. There are numerous instances where bracketing entire values are appropriate, for example with institutional authors. An example:

```
@book{SillyWalks1970,
 author = {{Ministry of Silly Walks}},
 location = {London},
 publisher = {We Publish Anything},
 title = {Handbook of Silly Walks},
 year = {1970}
}
```

The above bibtex entry yields (linebreaks added for readability):

```
[{u'publisher': u'We Publish Anything',
 u'title': u'Handbook of Silly Walks',
 u'author': u'Ministry of Silly Walks',
 'ID': 'SillyWalks1970',
 u'location': u'London',
 u'year': u'1970',
 'ENTRYTYPE': u'book'}]
```

Value of `author` should be `u'{Ministry of Silly Walks}'`, with brackets left untouched.

**Comment by sciunto** [comment]
Thank you for your report. Will be fixed by #64
